#!/usr/bin/env node
/**
 * Reads values from Infisical according to env.manifest.ts and reconciles
 * them with every place Gather's environment variables actually live.
 *
 *   node scripts/env.mjs generate            regenerate .env.example
 *   node scripts/env.mjs check               manifest only — no credentials
 *   node scripts/env.mjs check <environment> compare the manifest with reality
 *   node scripts/env.mjs apply <environment> write the manifest to reality
 *
 * Flags:
 *   --ci        when checking GitHub in a workflow, inspect the delivered job
 *               environment because GITHUB_TOKEN cannot list secrets.
 *   --only <k>  restrict to infisical or a destination kind.
 *   --pr <n>    the PR number, needed to name a per-PR preview Worker.
 *   --prune     delete values present at a destination but absent from the
 *               manifest. Requires a typed confirmation on production.
 *   --yes       skip that confirmation (for automation).
 *
 * Three rules this script will not break:
 *   1. It never writes an empty value. A value missing on this machine is
 *      skipped and reported — that is what stops `apply production` run from a
 *      laptop without the production secrets from blanking production.
 *   2. It never deletes without --prune.
 *   3. It never prints a secret's value.
 */
import { execFileSync } from 'node:child_process'
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { createInterface } from 'node:readline/promises'
import { fileURLToPath, pathToFileURL } from 'node:url'

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')

/** First bytes of every file this script writes. Its absence means a human owns the file. */
const GENERATED_MARKER = '# Generated by'
const { ENTRIES, ENVIRONMENTS, placementsFor } = await import(
  pathToFileURL(join(ROOT, 'env.manifest.ts'))
)
const {
  INFISICAL_ENVIRONMENTS,
  mergeInfisicalFolders,
  normalizeInfisicalExport,
  readInfisicalConfig,
} = await import(pathToFileURL(join(ROOT, 'scripts/env-source.mjs')))

// ---------------------------------------------------------------- utilities

const c = {
  red: (s) => `\x1b[31m${s}\x1b[0m`,
  green: (s) => `\x1b[32m${s}\x1b[0m`,
  yellow: (s) => `\x1b[33m${s}\x1b[0m`,
  dim: (s) => `\x1b[2m${s}\x1b[0m`,
  bold: (s) => `\x1b[1m${s}\x1b[0m`,
}

/**
 * Every secret value this run has loaded, so nothing can print one.
 *
 * A value reaches a CLI as an argument, so the failing command line contains it
 * — which means an unredacted error message publishes the secret to a terminal,
 * a CI log, or a bug report. Scrubbing at the single point where text leaves
 * this script is the only version of this that stays true as the script grows.
 */
const REDACT = new Set()

function redact(text) {
  let out = String(text)
  for (const secret of REDACT) {
    if (secret.length >= 4) out = out.split(secret).join('«redacted»')
  }
  return out
}

function run(command, args, { allowFail = false } = {}) {
  try {
    return execFileSync(command, args, {
      cwd: ROOT,
      encoding: 'utf8',
      stdio: ['pipe', 'pipe', 'pipe'],
      shell: process.platform === 'win32',
    })
  } catch (error) {
    if (allowFail) return null
    const detail = (error.stderr || error.message || '').toString().trim()
    throw new Error(redact(`${command} ${args.join(' ')} failed:\n${detail}`))
  }
}

/** The canonical key used in Infisical for a logical manifest entry. */
export function valueName(entry) {
  return entry.infisicalKey
}

function parseEnvText(text) {
  const values = {}
  for (const rawLine of text.split(/\r?\n/)) {
    const line = rawLine.trim()
    if (!line || line.startsWith('#')) continue
    const eq = line.indexOf('=')
    if (eq === -1) continue
    const key = line.slice(0, eq).trim()
    let value = line.slice(eq + 1).trim()
    if (
      (value.startsWith('"') && value.endsWith('"') && value.length > 1) ||
      (value.startsWith("'") && value.endsWith("'") && value.length > 1)
    ) {
      value = value.slice(1, -1)
    }
    if (value !== '') values[key] = value
  }
  return values
}

function readEnvFile(path) {
  const full = join(ROOT, path)
  return existsSync(full) ? parseEnvText(readFileSync(full, 'utf8')) : {}
}

function exportInfisical(environment, path) {
  const slug = INFISICAL_ENVIRONMENTS[environment]
  const output = run('infisical', [
    'export',
    '--format=json',
    `--env=${slug}`,
    `--path=${path}`,
    '--silent',
  ])
  try {
    return normalizeInfisicalExport(JSON.parse(output))
  } catch (error) {
    throw new Error(
      `Unable to parse Infisical ${slug}${path}: ${error.message}`,
    )
  }
}

/** Fetch every value in memory; /gather deliberately wins over /root. */
function readValues(environment) {
  readInfisicalConfig(ROOT)
  const rootValues = exportInfisical(environment, '/')
  const gatherValues = exportInfisical(environment, '/gather')
  const merged = mergeInfisicalFolders(rootValues, gatherValues)
  for (const entry of ENTRIES) {
    const value = merged.values[valueName(entry)]
    if (entry.secret && value) REDACT.add(String(value))
  }
  return { ...merged, rootValues, gatherValues }
}
function quoteIfNeeded(value) {
  return /[\s#'"]/.test(value) ? JSON.stringify(value) : value
}

// ------------------------------------------------------------- destinations
//
// Each reader returns { names: string[], values: Record<string, string> | null }.
// `values: null` means the destination can report which names exist but never
// what they hold — every secret store works this way, and it is the ceiling on
// what `check` can prove.

function convexArgs(target) {
  switch (target) {
    case 'dev':
      return {
        list: ['env', 'list'],
        set: ['env', 'set'],
        remove: ['env', 'remove'],
      }
    case 'production':
      return {
        list: ['env', 'list', '--prod'],
        set: ['env', 'set', '--prod'],
        remove: ['env', 'remove', '--prod'],
      }
    case 'staging':
      return {
        list: ['env', 'list', '--deployment', 'staging'],
        set: ['env', 'set', '--deployment', 'staging'],
        remove: ['env', 'remove', '--deployment', 'staging'],
      }
    case 'preview-default':
      // Preview backends are created per PR and inherit nothing, so the values
      // have to be project-level defaults rather than deployment vars.
      return {
        list: ['env', 'default', 'list', '--type', 'preview'],
        set: ['env', 'default', 'set', '--type', 'preview'],
        remove: ['env', 'default', 'remove', '--type', 'preview'],
      }
    default:
      throw new Error(`unknown convex target: ${target}`)
  }
}

function readConvex(target) {
  const output = run('npx', ['convex', ...convexArgs(target).list], {
    allowFail: true,
  })
  if (output === null) return null
  const values = parseEnvText(output)
  return { names: Object.keys(values), values }
}

function readWorker(worker) {
  const output = run(
    'npx',
    ['wrangler', 'secret', 'list', '--name', worker, '--format', 'json'],
    {
      allowFail: true,
    },
  )
  if (output === null) return null
  const start = output.indexOf('[')
  if (start === -1) return { names: [], values: null }
  try {
    const parsed = JSON.parse(output.slice(start))
    return { names: parsed.map((s) => s.name), values: null }
  } catch {
    return { names: [], values: null }
  }
}

function githubScopeArgs(scope) {
  return scope === 'repo' ? [] : ['--env', scope]
}

function readGithub(scope) {
  const scopeArgs = githubScopeArgs(scope)
  const secretsRaw = run(
    'gh',
    ['secret', 'list', ...scopeArgs, '--json', 'name'],
    {
      allowFail: true,
    },
  )
  const variablesRaw = run(
    'gh',
    ['variable', 'list', ...scopeArgs, '--json', 'name,value'],
    {
      allowFail: true,
    },
  )
  if (secretsRaw === null && variablesRaw === null) return null

  const secrets = secretsRaw ? JSON.parse(secretsRaw) : []
  const variables = variablesRaw ? JSON.parse(variablesRaw) : []
  const values = {}
  for (const variable of variables) values[variable.name] = variable.value
  return {
    names: [...secrets.map((s) => s.name), ...variables.map((v) => v.name)],
    // Variables are readable, secrets are not — so a value-diff is possible for
    // exactly the public half. That is what catches an environment-scoped value
    // that is missing and silently falling back to the repo-level one.
    values,
    secretNames: secrets.map((s) => s.name),
  }
}

function easArgs(args) {
  return ['--filter', '@gather/mobile', 'exec', 'eas', ...args]
}

function readEas(environment) {
  const manifestEnvironments =
    environment === 'development'
      ? ['local']
      : environment === 'preview'
        ? ['preview', 'stg']
        : ['production']
  const expectedNames = new Set(
    manifestEnvironments.flatMap((manifestEnvironment) =>
      placementsFor(manifestEnvironment)
        .filter(
          (placement) =>
            placement.destination.kind === 'eas' &&
            placement.destination.environment === environment,
        )
        .map((placement) => placement.name),
    ),
  )
  const names = []
  for (const name of expectedNames) {
    const output = run(
      'pnpm',
      easArgs([
        'env:get',
        environment,
        '--variable-name',
        name,
        '--format',
        'short',
        '--non-interactive',
      ]),
      { allowFail: true },
    )
    if (output !== null) names.push(name)
  }
  return { names, values: null }
}
function destinationLabel(destination) {
  switch (destination.kind) {
    case 'file':
      return destination.path
    case 'convex':
      return `convex:${destination.target}`
    case 'worker':
      return `worker:${destination.worker}`
    case 'github':
      return `github:${destination.scope}`
    case 'eas':
      return `eas:${destination.environment}`
  }
}

function readDestination(destination, { ci }) {
  switch (destination.kind) {
    case 'file': {
      const values = readEnvFile(destination.path)
      return { names: Object.keys(values), values }
    }
    case 'convex':
      return readConvex(destination.target)
    case 'worker':
      return readWorker(destination.worker)
    case 'eas':
      return readEas(destination.environment)
    case 'github':
      // A workflow cannot list its own secrets — GITHUB_TOKEN cannot be granted
      // secrets:read — but it does not need to: the job env is what GitHub
      // actually delivered, which is a stronger thing to assert than what the
      // settings page claims. Convex and the Worker are still checked for real,
      // and those are the ones a fresh environment silently lacks.
      return ci
        ? {
            names: Object.keys(process.env).filter((k) => process.env[k]),
            values: process.env,
          }
        : readGithub(destination.scope)
  }
}

// ------------------------------------------------------------------ writers

function writeConvex(target, name, value) {
  run('npx', ['convex', ...convexArgs(target).set, name, value])
}

function writeWorkerSecrets(worker, pairs) {
  if (pairs.length === 0) return
  // Cloudflare's only CLI-settable per-Worker store is secrets — `vars` live in
  // committed wrangler config, which cannot express a per-PR Worker. So public
  // values go in as secrets here too; the manifest's `secret` flag governs which
  // file holds a value and how GitHub stores it, not Cloudflare.
  const payload = JSON.stringify(Object.fromEntries(pairs))
  execFileSync('npx', ['wrangler', 'secret', 'bulk', '--name', worker], {
    cwd: ROOT,
    input: payload,
    encoding: 'utf8',
    stdio: ['pipe', 'inherit', 'inherit'],
    shell: process.platform === 'win32',
  })
}

function writeGithub(scope, name, value, secret) {
  const verb = secret ? 'secret' : 'variable'
  run('gh', [verb, 'set', name, ...githubScopeArgs(scope), '--body', value])
}
function writeEas(environment, name, value, secret) {
  run(
    'pnpm',
    easArgs([
      'env:set',
      '--environment',
      environment,
      '--name',
      name,
      '--value',
      value,
      '--visibility',
      secret ? 'secret' : 'plaintext',
      '--json',
      '--non-interactive',
    ]),
  )
}

// ----------------------------------------------------------------- generate

function renderEnvExample() {
  const lines = [
    '# Generated by `pnpm run env:generate` — do not edit by hand.',
    '#',
    '# This lists every canonical Infisical key and where Gather reads it.',
    '# Values live in the project selected by .infisical.json, under /',
    '# and /gather. Run `pnpm run env:apply local` to generate local files.',
    '#',
    '# Routing source of truth: env.manifest.ts',
    '',
  ]
  for (const entry of ENTRIES) {
    const places = Object.entries(entry.lands).map(
      ([consumer, landing]) =>
        `${landing.name} (${consumer}: ${landing.environments.join(', ')})`,
    )
    lines.push(`# ${entry.description}`)
    lines.push(`#   Infisical: ${entry.infisicalKey}`)
    for (const place of places) lines.push(`#   ${place}`)
    const flags = [
      entry.secret ? 'secret' : 'published',
      entry.optional ? 'optional' : 'required',
    ]
    lines.push(`#   ${flags.join(', ')}`)
    lines.push(`${entry.infisicalKey}=`)
    lines.push('')
  }
  return `${lines.join('\n').trimEnd()}\n`
}
function generate({ write }) {
  const rendered = renderEnvExample()
  const path = join(ROOT, '.env.example')
  const current = existsSync(path) ? readFileSync(path, 'utf8') : null
  if (current === rendered) return true
  if (!write) return false
  writeFileSync(path, rendered)
  return true
}

// -------------------------------------------------------------------- check

function checkManifest() {
  const problems = []

  for (const entry of ENTRIES) {
    const landings = Object.entries(entry.lands)
    if (landings.length === 0) {
      problems.push(`${entry.key}: declares no consumer, so it lands nowhere`)
    }
    if (entry.secret && entry.lands['vite-build']) {
      // The type forbids this; this catches a manifest edited as plain JS.
      problems.push(
        `${entry.key}: marked secret but read by the Vite build, which publishes it`,
      )
    }
    for (const [consumer, landing] of landings) {
      if (landing.environments.length === 0) {
        problems.push(`${entry.key}.${consumer}: applies to no environment`)
      }
      for (const environment of Object.keys(landing.suppliedIn ?? {})) {
        if (!landing.environments.includes(environment)) {
          problems.push(
            `${entry.key}.${consumer}: supplied in ${environment}, which it does not land in`,
          )
        }
      }
    }
  }

  // Two values reaching one destination under one name would silently overwrite
  // each other, and whichever lost would be invisible.
  for (const environment of ENVIRONMENTS) {
    const seen = new Map()
    for (const placement of placementsFor(environment, { prNumber: '0' })) {
      const slot = `${destinationLabel(placement.destination)}/${placement.name}`
      const previous = seen.get(slot)
      if (previous && previous !== placement.entry.key) {
        problems.push(
          `${slot}: claimed by both ${previous} and ${placement.entry.key}`,
        )
      }
      seen.set(slot, placement.entry.key)
    }
  }

  if (!generate({ write: false })) {
    problems.push('.env.example is stale — run `pnpm run env:generate`')
  }

  if (problems.length > 0) {
    console.error(c.bold('Manifest problems:'))
    for (const problem of problems) console.error(`  ${c.red('✗')} ${problem}`)
    return false
  }
  console.log(
    `${c.green('✓')} manifest consistent (${ENTRIES.length} values), .env.example current`,
  )
  return true
}

function checkEnvironment(environment, { ci, prNumber, only }) {
  const allPlacements = placementsFor(environment, { prNumber })
  const placements = allPlacements.filter(
    (placement) =>
      !only || only === 'infisical' || placement.destination.kind === only,
  )
  const source = readValues(environment)
  const values = source.values
  const cache = new Map()
  const failures = []
  const warnings = []
  const notes = source.overrides.map(
    (name) => `infisical:/gather overrides root/${name}`,
  )

  const declaredSourceNames = new Set(
    ENTRIES.map((entry) => entry.infisicalKey),
  )
  for (const name of Object.keys(source.gatherValues).sort()) {
    if (!declaredSourceNames.has(name)) {
      warnings.push(`infisical:/gather/${name} not in the manifest`)
    }
  }

  const applicableEntries = new Set(
    allPlacements.map((placement) => placement.entry),
  )
  for (const entry of applicableEntries) {
    const value = values[entry.infisicalKey]
    if (value !== undefined && value !== '') continue
    const message = `infisical:${INFISICAL_ENVIRONMENTS[environment]}/${entry.infisicalKey} missing`
    if (entry.optional) warnings.push(`${message} — optional`)
    else failures.push(message)
  }

  if (only !== 'infisical') {
    for (const placement of placements) {
      const label = destinationLabel(placement.destination)
      if (!cache.has(label))
        cache.set(label, readDestination(placement.destination, { ci }))
      const actual = cache.get(label)

      if (placement.suppliedBy) {
        notes.push(
          `${label}/${placement.name}: supplied by \`${placement.suppliedBy}\``,
        )
        continue
      }
      if (actual === null) {
        warnings.push(
          `${label}: unreachable — not checked (are you authenticated?)`,
        )
        continue
      }
      const present = actual.names.includes(placement.name)
      if (!present) {
        const message = `${label}/${placement.name} missing (${placement.entry.key})`
        if (placement.entry.optional) warnings.push(`${message} — optional`)
        else failures.push(message)
        continue
      }
      const expected = values[valueName(placement.entry)]
      const found = actual.values?.[placement.name]
      if (
        !placement.entry.secret &&
        expected !== undefined &&
        found !== undefined &&
        found !== expected
      ) {
        failures.push(
          `${label}/${placement.name} differs from Infisical (${placement.entry.key})`,
        )
        continue
      }
      console.log(`  ${c.green('✓')} ${label}/${placement.name}`)
    }
  }

  const declared = new Map()
  for (const placement of placements) {
    const label = destinationLabel(placement.destination)
    if (!declared.has(label)) declared.set(label, new Set())
    declared.get(label).add(placement.name)
  }
  const extras = []
  for (const [label, names] of declared) {
    const actual = cache.get(label)
    if (!actual) continue
    if (!label.startsWith('convex:') && !label.startsWith('worker:')) continue
    for (const name of actual.names) {
      if (!names.has(name)) extras.push(`${label}/${name}`)
    }
  }

  for (const note of notes) console.log(`  ${c.dim('·')} ${c.dim(note)}`)
  for (const warning of warnings) console.log(`  ${c.yellow('!')} ${warning}`)
  for (const extra of extras)
    console.log(`  ${c.yellow('+')} ${extra} not in the manifest`)
  for (const failure of failures) console.log(`  ${c.red('✗')} ${failure}`)

  if (failures.length > 0) {
    console.error(
      `\n${c.red(`${failures.length} problem(s)`)} in ${environment}`,
    )
    return false
  }
  console.log(`\n${c.green('✓')} ${environment} matches the manifest`)
  return true
}
// -------------------------------------------------------------------- apply

async function confirm(question) {
  const rl = createInterface({ input: process.stdin, output: process.stdout })
  const answer = await rl.question(question)
  rl.close()
  return answer.trim()
}

async function applyEnvironment(environment, { prune, yes, prNumber, only }) {
  const allPlacements = placementsFor(environment, { prNumber })
  const placements = allPlacements.filter(
    (placement) =>
      !only || (only !== 'infisical' && placement.destination.kind === only),
  )
  const source = readValues(environment)
  const values = source.values

  if (prune && environment === 'production' && !yes) {
    const answer = await confirm(
      `${c.yellow('--prune on production can remove a live value.')}\nType "production" to continue: `,
    )
    if (answer !== 'production') {
      console.error('Aborted.')
      return false
    }
  }

  const skipped = []
  const failed = []
  const workerBatches = new Map()
  let written = 0
  const attempt = (what, fn) => {
    try {
      fn()
      return true
    } catch (error) {
      failed.push(`${what}: ${error.message.split('\n')[0]}`)
      return false
    }
  }

  for (const placement of placements) {
    const label = destinationLabel(placement.destination)
    if (placement.suppliedBy) continue
    const value = values[valueName(placement.entry)]
    if (value === undefined || value === '') {
      skipped.push(`${label}/${placement.name} (${placement.entry.key})`)
      continue
    }

    switch (placement.destination.kind) {
      case 'file':
        break
      case 'convex':
        if (
          attempt(`${label}/${placement.name}`, () =>
            writeConvex(placement.destination.target, placement.name, value),
          )
        ) {
          written += 1
          console.log(`  ${c.green('→')} ${label}/${placement.name}`)
        }
        break
      case 'worker': {
        const batch = workerBatches.get(placement.destination.worker) ?? []
        batch.push([placement.name, value])
        workerBatches.set(placement.destination.worker, batch)
        break
      }
      case 'github':
        if (
          attempt(`${label}/${placement.name}`, () =>
            writeGithub(
              placement.destination.scope,
              placement.name,
              value,
              placement.entry.secret,
            ),
          )
        ) {
          written += 1
          console.log(`  ${c.green('→')} ${label}/${placement.name}`)
        }
        break
      case 'eas':
        if (
          attempt(`${label}/${placement.name}`, () =>
            writeEas(
              placement.destination.environment,
              placement.name,
              value,
              placement.entry.secret,
            ),
          )
        ) {
          written += 1
          console.log(`  ${c.green('→')} ${label}/${placement.name}`)
        }
        break
    }
  }

  for (const [worker, pairs] of workerBatches) {
    if (attempt(`worker:${worker}`, () => writeWorkerSecrets(worker, pairs))) {
      written += pairs.length
      console.log(`  ${c.green('→')} worker:${worker} ${pairs.length} value(s)`)
    }
  }

  const fileGroups = new Map()
  for (const placement of placements) {
    if (placement.destination.kind !== 'file' || placement.suppliedBy) continue
    const value = values[valueName(placement.entry)]
    if (value === undefined || value === '') continue
    const path = placement.destination.path
    if (!fileGroups.has(path)) fileGroups.set(path, [])
    fileGroups.get(path).push([placement.name, value])
  }
  for (const [path, pairs] of fileGroups) {
    const full = join(ROOT, path)
    if (
      existsSync(full) &&
      !readFileSync(full, 'utf8').startsWith(GENERATED_MARKER)
    ) {
      failed.push(
        `${path} already exists and was not generated — move its values to Infisical, then delete it`,
      )
      continue
    }
    const body = [
      `${GENERATED_MARKER} \`pnpm run env:apply ${environment}\` — do not edit by hand.`,
      '# Edit the value in Infisical, then apply again.',
      '',
      ...pairs.map(([name, value]) => `${name}=${quoteIfNeeded(value)}`),
      '',
    ].join('\n')
    writeFileSync(full, body)
    written += pairs.length
    console.log(`  ${c.green('→')} ${path} (${pairs.length} value(s))`)
  }

  if (prune) {
    const declared = new Map()
    for (const placement of placements) {
      const label = destinationLabel(placement.destination)
      if (!declared.has(label))
        declared.set(label, { placement, names: new Set() })
      declared.get(label).names.add(placement.name)
    }
    for (const [label, { placement, names }] of declared) {
      const { destination } = placement
      if (destination.kind !== 'convex' && destination.kind !== 'worker')
        continue
      const actual = readDestination(destination, { ci: false })
      if (!actual) continue
      for (const name of actual.names) {
        if (names.has(name)) continue
        if (destination.kind === 'convex') {
          run('npx', ['convex', ...convexArgs(destination.target).remove, name])
        } else if (destination.kind === 'worker') {
          run('npx', [
            'wrangler',
            'secret',
            'delete',
            name,
            '--name',
            destination.worker,
            '--force',
          ])
        } else {
          run(
            'pnpm',
            easArgs([
              'env:delete',
              '--environment',
              destination.environment,
              '--variable-name',
              name,
              '--non-interactive',
            ]),
          )
        }
        console.log(`  ${c.red('−')} ${label}/${name} removed`)
      }
    }
  }

  for (const override of source.overrides) {
    console.log(`  ${c.dim('·')} infisical:/gather overrides root/${override}`)
  }
  for (const skip of skipped) {
    console.log(
      `  ${c.yellow('!')} ${skip} — missing in Infisical, left unchanged`,
    )
  }
  for (const failure of failed) console.log(`  ${c.red('✗')} ${failure}`)

  const summary = `${environment}: ${written} written, ${skipped.length} skipped${
    failed.length > 0 ? `, ${failed.length} failed` : ''
  }${prune ? ', pruned' : ''}`
  console.log(`\n${failed.length > 0 ? c.red('✗') : c.green('✓')} ${summary}`)
  return failed.length === 0
}
// --------------------------------------------------------------------- main

function usage() {
  console.error(
    [
      'Usage:',
      '  node scripts/env.mjs generate',
      '  node scripts/env.mjs check [local|preview|stg|production] [--ci] [--only <kind>] [--pr <n>]',
      '  node scripts/env.mjs apply <local|preview|stg|production>',
      '        [--only infisical|file|convex|worker|github|eas] [--pr <n>] [--prune] [--yes]',
    ].join('\n'),
  )
}

const argv = process.argv.slice(2)
const flagValue = (flag, fallback) => {
  const index = argv.indexOf(flag)
  return index === -1 ? fallback : argv[index + 1]
}
const flags = {
  ci: argv.includes('--ci'),
  prune: argv.includes('--prune'),
  yes: argv.includes('--yes'),
  prNumber: flagValue('--pr', process.env.PR_NUMBER),
  only: flagValue('--only', undefined),
}
const VALUED_FLAGS = new Set(['--pr', '--only'])
const positional = argv.filter(
  (a, i) => !a.startsWith('--') && !VALUED_FLAGS.has(argv[i - 1]),
)

if (
  flags.only &&
  !['infisical', 'file', 'convex', 'worker', 'github', 'eas'].includes(
    flags.only,
  )
) {
  console.error(
    `Unknown --only "${flags.only}". Expected: infisical, file, convex, worker, github, eas`,
  )
  process.exit(2)
}
const [command, environment] = positional

if (environment && !ENVIRONMENTS.includes(environment)) {
  console.error(
    `Unknown environment "${environment}". Expected one of: ${ENVIRONMENTS.join(', ')}`,
  )
  process.exit(2)
}

let ok = false
switch (command) {
  case 'generate': {
    generate({ write: true })
    console.log(`${c.green('✓')} .env.example regenerated from env.manifest.ts`)
    ok = true
    break
  }
  case 'check':
    ok = environment
      ? checkEnvironment(environment, {
          ci: flags.ci,
          prNumber: flags.prNumber,
          only: flags.only,
        })
      : checkManifest()
    break
  case 'apply':
    if (!environment) {
      usage()
      process.exit(2)
    }
    ok = await applyEnvironment(environment, flags)
    break
  default:
    usage()
    process.exit(2)
}

process.exit(ok ? 0 : 1)
