/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppGroupsRouteImport } from './routes/_app/groups'
import { Route as AppAccountRouteImport } from './routes/_app/account'
import { Route as AppSplatRouteImport } from './routes/_app/$'
import { Route as AppIntegrationsCallbackRouteImport } from './routes/_app/integrations.callback'
import { Route as AppGGroupSlugRouteImport } from './routes/_app/g/$groupSlug'
import { Route as AppGGroupSlugIndexRouteImport } from './routes/_app/g/$groupSlug/index'
import { Route as AppGGroupSlugWinesRouteImport } from './routes/_app/g/$groupSlug/wines'
import { Route as AppGGroupSlugTasksRouteImport } from './routes/_app/g/$groupSlug/tasks'
import { Route as AppGGroupSlugSettingsRouteImport } from './routes/_app/g/$groupSlug/settings'
import { Route as AppGGroupSlugPantryRouteImport } from './routes/_app/g/$groupSlug/pantry'
import { Route as AppGGroupSlugNutritionRouteImport } from './routes/_app/g/$groupSlug/nutrition'
import { Route as AppGGroupSlugNotesRouteImport } from './routes/_app/g/$groupSlug/notes'
import { Route as AppGGroupSlugMealPlannerRouteImport } from './routes/_app/g/$groupSlug/meal-planner'
import { Route as AppGGroupSlugGroceriesRouteImport } from './routes/_app/g/$groupSlug/groceries'
import { Route as AppGGroupSlugFinancesRouteImport } from './routes/_app/g/$groupSlug/finances'
import { Route as AppGGroupSlugCombosRouteImport } from './routes/_app/g/$groupSlug/combos'
import { Route as AppGGroupSlugCheesesRouteImport } from './routes/_app/g/$groupSlug/cheeses'
import { Route as AppGGroupSlugCalendarRouteImport } from './routes/_app/g/$groupSlug/calendar'
import { Route as AppGGroupSlugBeersRouteImport } from './routes/_app/g/$groupSlug/beers'
import { Route as AppGGroupSlugAllRouteImport } from './routes/_app/g/$groupSlug/all'
import { Route as AppGGroupSlugRecipesIndexRouteImport } from './routes/_app/g/$groupSlug/recipes/index'
import { Route as AppGGroupSlugNutritionIndexRouteImport } from './routes/_app/g/$groupSlug/nutrition/index'
import { Route as AppGGroupSlugFoodsIndexRouteImport } from './routes/_app/g/$groupSlug/foods/index'
import { Route as AppGGroupSlugBabyIndexRouteImport } from './routes/_app/g/$groupSlug/baby/index'
import { Route as AppGGroupSlugRecipesNewRouteImport } from './routes/_app/g/$groupSlug/recipes/new'
import { Route as AppGGroupSlugNutritionAddRouteImport } from './routes/_app/g/$groupSlug/nutrition/add'
import { Route as AppGGroupSlugFoodsNewRouteImport } from './routes/_app/g/$groupSlug/foods/new'
import { Route as AppGGroupSlugBabyNewRouteImport } from './routes/_app/g/$groupSlug/baby/new'
import { Route as AppGGroupSlugRecipesRecipeIdIndexRouteImport } from './routes/_app/g/$groupSlug/recipes/$recipeId.index'
import { Route as AppGGroupSlugFoodsFoodIdIndexRouteImport } from './routes/_app/g/$groupSlug/foods/$foodId.index'
import { Route as AppGGroupSlugBabyBabyIdIndexRouteImport } from './routes/_app/g/$groupSlug/baby/$babyId.index'
import { Route as AppGGroupSlugRecipesRecipeIdEditRouteImport } from './routes/_app/g/$groupSlug/recipes/$recipeId.edit'
import { Route as AppGGroupSlugFoodsFoodIdEditRouteImport } from './routes/_app/g/$groupSlug/foods/$foodId.edit'
import { Route as AppGGroupSlugBabyBabyIdEditRouteImport } from './routes/_app/g/$groupSlug/baby/$babyId.edit'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppGroupsRoute = AppGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppSplatRoute = AppSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsCallbackRoute = AppIntegrationsCallbackRouteImport.update({
  id: '/integrations/callback',
  path: '/integrations/callback',
  getParentRoute: () => AppRoute,
} as any)
const AppGGroupSlugRoute = AppGGroupSlugRouteImport.update({
  id: '/g/$groupSlug',
  path: '/g/$groupSlug',
  getParentRoute: () => AppRoute,
} as any)
const AppGGroupSlugIndexRoute = AppGGroupSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppGGroupSlugRoute,
} as any)
const AppGGroupSlugWinesRoute = AppGGroupSlugWinesRouteImport.update({
  id: '/wines',
  path: '/wines',
  getParentRoute: () => AppGGroupSlugRoute,
} as any)
const AppGGroupSlugTasksRoute = AppGGroupSlugTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppGGroupSlugRoute,
} as any)
const AppGGroupSlugSettingsRoute = AppGGroupSlugSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppGGroupSlugRoute,
} as any)
const AppGGroupSlugPantryRoute = AppGGroupSlugPantryRouteImport.update({
  id: '/pantry',
  path: '/pantry',
  getParentRoute: () => AppGGroupSlugRoute,
} as any)
const AppGGroupSlugNutritionRoute = AppGGroupSlugNutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => AppGGroupSlugRoute,
} as any)
const AppGGroupSlugNotesRoute = AppGGroupSlugNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AppGGroupSlugRoute,
} as any)
const AppGGroupSlugMealPlannerRoute =
  AppGGroupSlugMealPlannerRouteImport.update({
    id: '/meal-planner',
    path: '/meal-planner',
    getParentRoute: () => AppGGroupSlugRoute,
  } as any)
const AppGGroupSlugGroceriesRoute = AppGGroupSlugGroceriesRouteImport.update({
  id: '/groceries',
  path: '/groceries',
  getParentRoute: () => AppGGroupSlugRoute,
} as any)
const AppGGroupSlugFinancesRoute = AppGGroupSlugFinancesRouteImport.update({
  id: '/finances',
  path: '/finances',
  getParentRoute: () => AppGGroupSlugRoute,
} as any)
const AppGGroupSlugCombosRoute = AppGGroupSlugCombosRouteImport.update({
  id: '/combos',
  path: '/combos',
  getParentRoute: () => AppGGroupSlugRoute,
} as any)
const AppGGroupSlugCheesesRoute = AppGGroupSlugCheesesRouteImport.update({
  id: '/cheeses',
  path: '/cheeses',
  getParentRoute: () => AppGGroupSlugRoute,
} as any)
const AppGGroupSlugCalendarRoute = AppGGroupSlugCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppGGroupSlugRoute,
} as any)
const AppGGroupSlugBeersRoute = AppGGroupSlugBeersRouteImport.update({
  id: '/beers',
  path: '/beers',
  getParentRoute: () => AppGGroupSlugRoute,
} as any)
const AppGGroupSlugAllRoute = AppGGroupSlugAllRouteImport.update({
  id: '/all',
  path: '/all',
  getParentRoute: () => AppGGroupSlugRoute,
} as any)
const AppGGroupSlugRecipesIndexRoute =
  AppGGroupSlugRecipesIndexRouteImport.update({
    id: '/recipes/',
    path: '/recipes/',
    getParentRoute: () => AppGGroupSlugRoute,
  } as any)
const AppGGroupSlugNutritionIndexRoute =
  AppGGroupSlugNutritionIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppGGroupSlugNutritionRoute,
  } as any)
const AppGGroupSlugFoodsIndexRoute = AppGGroupSlugFoodsIndexRouteImport.update({
  id: '/foods/',
  path: '/foods/',
  getParentRoute: () => AppGGroupSlugRoute,
} as any)
const AppGGroupSlugBabyIndexRoute = AppGGroupSlugBabyIndexRouteImport.update({
  id: '/baby/',
  path: '/baby/',
  getParentRoute: () => AppGGroupSlugRoute,
} as any)
const AppGGroupSlugRecipesNewRoute = AppGGroupSlugRecipesNewRouteImport.update({
  id: '/recipes/new',
  path: '/recipes/new',
  getParentRoute: () => AppGGroupSlugRoute,
} as any)
const AppGGroupSlugNutritionAddRoute =
  AppGGroupSlugNutritionAddRouteImport.update({
    id: '/add',
    path: '/add',
    getParentRoute: () => AppGGroupSlugNutritionRoute,
  } as any)
const AppGGroupSlugFoodsNewRoute = AppGGroupSlugFoodsNewRouteImport.update({
  id: '/foods/new',
  path: '/foods/new',
  getParentRoute: () => AppGGroupSlugRoute,
} as any)
const AppGGroupSlugBabyNewRoute = AppGGroupSlugBabyNewRouteImport.update({
  id: '/baby/new',
  path: '/baby/new',
  getParentRoute: () => AppGGroupSlugRoute,
} as any)
const AppGGroupSlugRecipesRecipeIdIndexRoute =
  AppGGroupSlugRecipesRecipeIdIndexRouteImport.update({
    id: '/recipes/$recipeId/',
    path: '/recipes/$recipeId/',
    getParentRoute: () => AppGGroupSlugRoute,
  } as any)
const AppGGroupSlugFoodsFoodIdIndexRoute =
  AppGGroupSlugFoodsFoodIdIndexRouteImport.update({
    id: '/foods/$foodId/',
    path: '/foods/$foodId/',
    getParentRoute: () => AppGGroupSlugRoute,
  } as any)
const AppGGroupSlugBabyBabyIdIndexRoute =
  AppGGroupSlugBabyBabyIdIndexRouteImport.update({
    id: '/baby/$babyId/',
    path: '/baby/$babyId/',
    getParentRoute: () => AppGGroupSlugRoute,
  } as any)
const AppGGroupSlugRecipesRecipeIdEditRoute =
  AppGGroupSlugRecipesRecipeIdEditRouteImport.update({
    id: '/recipes/$recipeId/edit',
    path: '/recipes/$recipeId/edit',
    getParentRoute: () => AppGGroupSlugRoute,
  } as any)
const AppGGroupSlugFoodsFoodIdEditRoute =
  AppGGroupSlugFoodsFoodIdEditRouteImport.update({
    id: '/foods/$foodId/edit',
    path: '/foods/$foodId/edit',
    getParentRoute: () => AppGGroupSlugRoute,
  } as any)
const AppGGroupSlugBabyBabyIdEditRoute =
  AppGGroupSlugBabyBabyIdEditRouteImport.update({
    id: '/baby/$babyId/edit',
    path: '/baby/$babyId/edit',
    getParentRoute: () => AppGGroupSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/about': typeof AboutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/$': typeof AppSplatRoute
  '/account': typeof AppAccountRoute
  '/groups': typeof AppGroupsRoute
  '/settings': typeof AppSettingsRoute
  '/g/$groupSlug': typeof AppGGroupSlugRouteWithChildren
  '/integrations/callback': typeof AppIntegrationsCallbackRoute
  '/g/$groupSlug/all': typeof AppGGroupSlugAllRoute
  '/g/$groupSlug/beers': typeof AppGGroupSlugBeersRoute
  '/g/$groupSlug/calendar': typeof AppGGroupSlugCalendarRoute
  '/g/$groupSlug/cheeses': typeof AppGGroupSlugCheesesRoute
  '/g/$groupSlug/combos': typeof AppGGroupSlugCombosRoute
  '/g/$groupSlug/finances': typeof AppGGroupSlugFinancesRoute
  '/g/$groupSlug/groceries': typeof AppGGroupSlugGroceriesRoute
  '/g/$groupSlug/meal-planner': typeof AppGGroupSlugMealPlannerRoute
  '/g/$groupSlug/notes': typeof AppGGroupSlugNotesRoute
  '/g/$groupSlug/nutrition': typeof AppGGroupSlugNutritionRouteWithChildren
  '/g/$groupSlug/pantry': typeof AppGGroupSlugPantryRoute
  '/g/$groupSlug/settings': typeof AppGGroupSlugSettingsRoute
  '/g/$groupSlug/tasks': typeof AppGGroupSlugTasksRoute
  '/g/$groupSlug/wines': typeof AppGGroupSlugWinesRoute
  '/g/$groupSlug/': typeof AppGGroupSlugIndexRoute
  '/g/$groupSlug/baby/new': typeof AppGGroupSlugBabyNewRoute
  '/g/$groupSlug/foods/new': typeof AppGGroupSlugFoodsNewRoute
  '/g/$groupSlug/nutrition/add': typeof AppGGroupSlugNutritionAddRoute
  '/g/$groupSlug/recipes/new': typeof AppGGroupSlugRecipesNewRoute
  '/g/$groupSlug/baby/': typeof AppGGroupSlugBabyIndexRoute
  '/g/$groupSlug/foods/': typeof AppGGroupSlugFoodsIndexRoute
  '/g/$groupSlug/nutrition/': typeof AppGGroupSlugNutritionIndexRoute
  '/g/$groupSlug/recipes/': typeof AppGGroupSlugRecipesIndexRoute
  '/g/$groupSlug/baby/$babyId/edit': typeof AppGGroupSlugBabyBabyIdEditRoute
  '/g/$groupSlug/foods/$foodId/edit': typeof AppGGroupSlugFoodsFoodIdEditRoute
  '/g/$groupSlug/recipes/$recipeId/edit': typeof AppGGroupSlugRecipesRecipeIdEditRoute
  '/g/$groupSlug/baby/$babyId/': typeof AppGGroupSlugBabyBabyIdIndexRoute
  '/g/$groupSlug/foods/$foodId/': typeof AppGGroupSlugFoodsFoodIdIndexRoute
  '/g/$groupSlug/recipes/$recipeId/': typeof AppGGroupSlugRecipesRecipeIdIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof AboutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/$': typeof AppSplatRoute
  '/account': typeof AppAccountRoute
  '/groups': typeof AppGroupsRoute
  '/settings': typeof AppSettingsRoute
  '/': typeof AppIndexRoute
  '/integrations/callback': typeof AppIntegrationsCallbackRoute
  '/g/$groupSlug/all': typeof AppGGroupSlugAllRoute
  '/g/$groupSlug/beers': typeof AppGGroupSlugBeersRoute
  '/g/$groupSlug/calendar': typeof AppGGroupSlugCalendarRoute
  '/g/$groupSlug/cheeses': typeof AppGGroupSlugCheesesRoute
  '/g/$groupSlug/combos': typeof AppGGroupSlugCombosRoute
  '/g/$groupSlug/finances': typeof AppGGroupSlugFinancesRoute
  '/g/$groupSlug/groceries': typeof AppGGroupSlugGroceriesRoute
  '/g/$groupSlug/meal-planner': typeof AppGGroupSlugMealPlannerRoute
  '/g/$groupSlug/notes': typeof AppGGroupSlugNotesRoute
  '/g/$groupSlug/pantry': typeof AppGGroupSlugPantryRoute
  '/g/$groupSlug/settings': typeof AppGGroupSlugSettingsRoute
  '/g/$groupSlug/tasks': typeof AppGGroupSlugTasksRoute
  '/g/$groupSlug/wines': typeof AppGGroupSlugWinesRoute
  '/g/$groupSlug': typeof AppGGroupSlugIndexRoute
  '/g/$groupSlug/baby/new': typeof AppGGroupSlugBabyNewRoute
  '/g/$groupSlug/foods/new': typeof AppGGroupSlugFoodsNewRoute
  '/g/$groupSlug/nutrition/add': typeof AppGGroupSlugNutritionAddRoute
  '/g/$groupSlug/recipes/new': typeof AppGGroupSlugRecipesNewRoute
  '/g/$groupSlug/baby': typeof AppGGroupSlugBabyIndexRoute
  '/g/$groupSlug/foods': typeof AppGGroupSlugFoodsIndexRoute
  '/g/$groupSlug/nutrition': typeof AppGGroupSlugNutritionIndexRoute
  '/g/$groupSlug/recipes': typeof AppGGroupSlugRecipesIndexRoute
  '/g/$groupSlug/baby/$babyId/edit': typeof AppGGroupSlugBabyBabyIdEditRoute
  '/g/$groupSlug/foods/$foodId/edit': typeof AppGGroupSlugFoodsFoodIdEditRoute
  '/g/$groupSlug/recipes/$recipeId/edit': typeof AppGGroupSlugRecipesRecipeIdEditRoute
  '/g/$groupSlug/baby/$babyId': typeof AppGGroupSlugBabyBabyIdIndexRoute
  '/g/$groupSlug/foods/$foodId': typeof AppGGroupSlugFoodsFoodIdIndexRoute
  '/g/$groupSlug/recipes/$recipeId': typeof AppGGroupSlugRecipesRecipeIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/about': typeof AboutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_app/$': typeof AppSplatRoute
  '/_app/account': typeof AppAccountRoute
  '/_app/groups': typeof AppGroupsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/g/$groupSlug': typeof AppGGroupSlugRouteWithChildren
  '/_app/integrations/callback': typeof AppIntegrationsCallbackRoute
  '/_app/g/$groupSlug/all': typeof AppGGroupSlugAllRoute
  '/_app/g/$groupSlug/beers': typeof AppGGroupSlugBeersRoute
  '/_app/g/$groupSlug/calendar': typeof AppGGroupSlugCalendarRoute
  '/_app/g/$groupSlug/cheeses': typeof AppGGroupSlugCheesesRoute
  '/_app/g/$groupSlug/combos': typeof AppGGroupSlugCombosRoute
  '/_app/g/$groupSlug/finances': typeof AppGGroupSlugFinancesRoute
  '/_app/g/$groupSlug/groceries': typeof AppGGroupSlugGroceriesRoute
  '/_app/g/$groupSlug/meal-planner': typeof AppGGroupSlugMealPlannerRoute
  '/_app/g/$groupSlug/notes': typeof AppGGroupSlugNotesRoute
  '/_app/g/$groupSlug/nutrition': typeof AppGGroupSlugNutritionRouteWithChildren
  '/_app/g/$groupSlug/pantry': typeof AppGGroupSlugPantryRoute
  '/_app/g/$groupSlug/settings': typeof AppGGroupSlugSettingsRoute
  '/_app/g/$groupSlug/tasks': typeof AppGGroupSlugTasksRoute
  '/_app/g/$groupSlug/wines': typeof AppGGroupSlugWinesRoute
  '/_app/g/$groupSlug/': typeof AppGGroupSlugIndexRoute
  '/_app/g/$groupSlug/baby/new': typeof AppGGroupSlugBabyNewRoute
  '/_app/g/$groupSlug/foods/new': typeof AppGGroupSlugFoodsNewRoute
  '/_app/g/$groupSlug/nutrition/add': typeof AppGGroupSlugNutritionAddRoute
  '/_app/g/$groupSlug/recipes/new': typeof AppGGroupSlugRecipesNewRoute
  '/_app/g/$groupSlug/baby/': typeof AppGGroupSlugBabyIndexRoute
  '/_app/g/$groupSlug/foods/': typeof AppGGroupSlugFoodsIndexRoute
  '/_app/g/$groupSlug/nutrition/': typeof AppGGroupSlugNutritionIndexRoute
  '/_app/g/$groupSlug/recipes/': typeof AppGGroupSlugRecipesIndexRoute
  '/_app/g/$groupSlug/baby/$babyId/edit': typeof AppGGroupSlugBabyBabyIdEditRoute
  '/_app/g/$groupSlug/foods/$foodId/edit': typeof AppGGroupSlugFoodsFoodIdEditRoute
  '/_app/g/$groupSlug/recipes/$recipeId/edit': typeof AppGGroupSlugRecipesRecipeIdEditRoute
  '/_app/g/$groupSlug/baby/$babyId/': typeof AppGGroupSlugBabyBabyIdIndexRoute
  '/_app/g/$groupSlug/foods/$foodId/': typeof AppGGroupSlugFoodsFoodIdIndexRoute
  '/_app/g/$groupSlug/recipes/$recipeId/': typeof AppGGroupSlugRecipesRecipeIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/$'
    | '/account'
    | '/groups'
    | '/settings'
    | '/g/$groupSlug'
    | '/integrations/callback'
    | '/g/$groupSlug/all'
    | '/g/$groupSlug/beers'
    | '/g/$groupSlug/calendar'
    | '/g/$groupSlug/cheeses'
    | '/g/$groupSlug/combos'
    | '/g/$groupSlug/finances'
    | '/g/$groupSlug/groceries'
    | '/g/$groupSlug/meal-planner'
    | '/g/$groupSlug/notes'
    | '/g/$groupSlug/nutrition'
    | '/g/$groupSlug/pantry'
    | '/g/$groupSlug/settings'
    | '/g/$groupSlug/tasks'
    | '/g/$groupSlug/wines'
    | '/g/$groupSlug/'
    | '/g/$groupSlug/baby/new'
    | '/g/$groupSlug/foods/new'
    | '/g/$groupSlug/nutrition/add'
    | '/g/$groupSlug/recipes/new'
    | '/g/$groupSlug/baby/'
    | '/g/$groupSlug/foods/'
    | '/g/$groupSlug/nutrition/'
    | '/g/$groupSlug/recipes/'
    | '/g/$groupSlug/baby/$babyId/edit'
    | '/g/$groupSlug/foods/$foodId/edit'
    | '/g/$groupSlug/recipes/$recipeId/edit'
    | '/g/$groupSlug/baby/$babyId/'
    | '/g/$groupSlug/foods/$foodId/'
    | '/g/$groupSlug/recipes/$recipeId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/$'
    | '/account'
    | '/groups'
    | '/settings'
    | '/'
    | '/integrations/callback'
    | '/g/$groupSlug/all'
    | '/g/$groupSlug/beers'
    | '/g/$groupSlug/calendar'
    | '/g/$groupSlug/cheeses'
    | '/g/$groupSlug/combos'
    | '/g/$groupSlug/finances'
    | '/g/$groupSlug/groceries'
    | '/g/$groupSlug/meal-planner'
    | '/g/$groupSlug/notes'
    | '/g/$groupSlug/pantry'
    | '/g/$groupSlug/settings'
    | '/g/$groupSlug/tasks'
    | '/g/$groupSlug/wines'
    | '/g/$groupSlug'
    | '/g/$groupSlug/baby/new'
    | '/g/$groupSlug/foods/new'
    | '/g/$groupSlug/nutrition/add'
    | '/g/$groupSlug/recipes/new'
    | '/g/$groupSlug/baby'
    | '/g/$groupSlug/foods'
    | '/g/$groupSlug/nutrition'
    | '/g/$groupSlug/recipes'
    | '/g/$groupSlug/baby/$babyId/edit'
    | '/g/$groupSlug/foods/$foodId/edit'
    | '/g/$groupSlug/recipes/$recipeId/edit'
    | '/g/$groupSlug/baby/$babyId'
    | '/g/$groupSlug/foods/$foodId'
    | '/g/$groupSlug/recipes/$recipeId'
  id:
    | '__root__'
    | '/_app'
    | '/about'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/_app/$'
    | '/_app/account'
    | '/_app/groups'
    | '/_app/settings'
    | '/_app/'
    | '/_app/g/$groupSlug'
    | '/_app/integrations/callback'
    | '/_app/g/$groupSlug/all'
    | '/_app/g/$groupSlug/beers'
    | '/_app/g/$groupSlug/calendar'
    | '/_app/g/$groupSlug/cheeses'
    | '/_app/g/$groupSlug/combos'
    | '/_app/g/$groupSlug/finances'
    | '/_app/g/$groupSlug/groceries'
    | '/_app/g/$groupSlug/meal-planner'
    | '/_app/g/$groupSlug/notes'
    | '/_app/g/$groupSlug/nutrition'
    | '/_app/g/$groupSlug/pantry'
    | '/_app/g/$groupSlug/settings'
    | '/_app/g/$groupSlug/tasks'
    | '/_app/g/$groupSlug/wines'
    | '/_app/g/$groupSlug/'
    | '/_app/g/$groupSlug/baby/new'
    | '/_app/g/$groupSlug/foods/new'
    | '/_app/g/$groupSlug/nutrition/add'
    | '/_app/g/$groupSlug/recipes/new'
    | '/_app/g/$groupSlug/baby/'
    | '/_app/g/$groupSlug/foods/'
    | '/_app/g/$groupSlug/nutrition/'
    | '/_app/g/$groupSlug/recipes/'
    | '/_app/g/$groupSlug/baby/$babyId/edit'
    | '/_app/g/$groupSlug/foods/$foodId/edit'
    | '/_app/g/$groupSlug/recipes/$recipeId/edit'
    | '/_app/g/$groupSlug/baby/$babyId/'
    | '/_app/g/$groupSlug/foods/$foodId/'
    | '/_app/g/$groupSlug/recipes/$recipeId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AboutRoute: typeof AboutRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/groups': {
      id: '/_app/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof AppGroupsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$': {
      id: '/_app/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof AppSplatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integrations/callback': {
      id: '/_app/integrations/callback'
      path: '/integrations/callback'
      fullPath: '/integrations/callback'
      preLoaderRoute: typeof AppIntegrationsCallbackRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/g/$groupSlug': {
      id: '/_app/g/$groupSlug'
      path: '/g/$groupSlug'
      fullPath: '/g/$groupSlug'
      preLoaderRoute: typeof AppGGroupSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/g/$groupSlug/': {
      id: '/_app/g/$groupSlug/'
      path: '/'
      fullPath: '/g/$groupSlug/'
      preLoaderRoute: typeof AppGGroupSlugIndexRouteImport
      parentRoute: typeof AppGGroupSlugRoute
    }
    '/_app/g/$groupSlug/wines': {
      id: '/_app/g/$groupSlug/wines'
      path: '/wines'
      fullPath: '/g/$groupSlug/wines'
      preLoaderRoute: typeof AppGGroupSlugWinesRouteImport
      parentRoute: typeof AppGGroupSlugRoute
    }
    '/_app/g/$groupSlug/tasks': {
      id: '/_app/g/$groupSlug/tasks'
      path: '/tasks'
      fullPath: '/g/$groupSlug/tasks'
      preLoaderRoute: typeof AppGGroupSlugTasksRouteImport
      parentRoute: typeof AppGGroupSlugRoute
    }
    '/_app/g/$groupSlug/settings': {
      id: '/_app/g/$groupSlug/settings'
      path: '/settings'
      fullPath: '/g/$groupSlug/settings'
      preLoaderRoute: typeof AppGGroupSlugSettingsRouteImport
      parentRoute: typeof AppGGroupSlugRoute
    }
    '/_app/g/$groupSlug/pantry': {
      id: '/_app/g/$groupSlug/pantry'
      path: '/pantry'
      fullPath: '/g/$groupSlug/pantry'
      preLoaderRoute: typeof AppGGroupSlugPantryRouteImport
      parentRoute: typeof AppGGroupSlugRoute
    }
    '/_app/g/$groupSlug/nutrition': {
      id: '/_app/g/$groupSlug/nutrition'
      path: '/nutrition'
      fullPath: '/g/$groupSlug/nutrition'
      preLoaderRoute: typeof AppGGroupSlugNutritionRouteImport
      parentRoute: typeof AppGGroupSlugRoute
    }
    '/_app/g/$groupSlug/notes': {
      id: '/_app/g/$groupSlug/notes'
      path: '/notes'
      fullPath: '/g/$groupSlug/notes'
      preLoaderRoute: typeof AppGGroupSlugNotesRouteImport
      parentRoute: typeof AppGGroupSlugRoute
    }
    '/_app/g/$groupSlug/meal-planner': {
      id: '/_app/g/$groupSlug/meal-planner'
      path: '/meal-planner'
      fullPath: '/g/$groupSlug/meal-planner'
      preLoaderRoute: typeof AppGGroupSlugMealPlannerRouteImport
      parentRoute: typeof AppGGroupSlugRoute
    }
    '/_app/g/$groupSlug/groceries': {
      id: '/_app/g/$groupSlug/groceries'
      path: '/groceries'
      fullPath: '/g/$groupSlug/groceries'
      preLoaderRoute: typeof AppGGroupSlugGroceriesRouteImport
      parentRoute: typeof AppGGroupSlugRoute
    }
    '/_app/g/$groupSlug/finances': {
      id: '/_app/g/$groupSlug/finances'
      path: '/finances'
      fullPath: '/g/$groupSlug/finances'
      preLoaderRoute: typeof AppGGroupSlugFinancesRouteImport
      parentRoute: typeof AppGGroupSlugRoute
    }
    '/_app/g/$groupSlug/combos': {
      id: '/_app/g/$groupSlug/combos'
      path: '/combos'
      fullPath: '/g/$groupSlug/combos'
      preLoaderRoute: typeof AppGGroupSlugCombosRouteImport
      parentRoute: typeof AppGGroupSlugRoute
    }
    '/_app/g/$groupSlug/cheeses': {
      id: '/_app/g/$groupSlug/cheeses'
      path: '/cheeses'
      fullPath: '/g/$groupSlug/cheeses'
      preLoaderRoute: typeof AppGGroupSlugCheesesRouteImport
      parentRoute: typeof AppGGroupSlugRoute
    }
    '/_app/g/$groupSlug/calendar': {
      id: '/_app/g/$groupSlug/calendar'
      path: '/calendar'
      fullPath: '/g/$groupSlug/calendar'
      preLoaderRoute: typeof AppGGroupSlugCalendarRouteImport
      parentRoute: typeof AppGGroupSlugRoute
    }
    '/_app/g/$groupSlug/beers': {
      id: '/_app/g/$groupSlug/beers'
      path: '/beers'
      fullPath: '/g/$groupSlug/beers'
      preLoaderRoute: typeof AppGGroupSlugBeersRouteImport
      parentRoute: typeof AppGGroupSlugRoute
    }
    '/_app/g/$groupSlug/all': {
      id: '/_app/g/$groupSlug/all'
      path: '/all'
      fullPath: '/g/$groupSlug/all'
      preLoaderRoute: typeof AppGGroupSlugAllRouteImport
      parentRoute: typeof AppGGroupSlugRoute
    }
    '/_app/g/$groupSlug/recipes/': {
      id: '/_app/g/$groupSlug/recipes/'
      path: '/recipes'
      fullPath: '/g/$groupSlug/recipes/'
      preLoaderRoute: typeof AppGGroupSlugRecipesIndexRouteImport
      parentRoute: typeof AppGGroupSlugRoute
    }
    '/_app/g/$groupSlug/nutrition/': {
      id: '/_app/g/$groupSlug/nutrition/'
      path: '/'
      fullPath: '/g/$groupSlug/nutrition/'
      preLoaderRoute: typeof AppGGroupSlugNutritionIndexRouteImport
      parentRoute: typeof AppGGroupSlugNutritionRoute
    }
    '/_app/g/$groupSlug/foods/': {
      id: '/_app/g/$groupSlug/foods/'
      path: '/foods'
      fullPath: '/g/$groupSlug/foods/'
      preLoaderRoute: typeof AppGGroupSlugFoodsIndexRouteImport
      parentRoute: typeof AppGGroupSlugRoute
    }
    '/_app/g/$groupSlug/baby/': {
      id: '/_app/g/$groupSlug/baby/'
      path: '/baby'
      fullPath: '/g/$groupSlug/baby/'
      preLoaderRoute: typeof AppGGroupSlugBabyIndexRouteImport
      parentRoute: typeof AppGGroupSlugRoute
    }
    '/_app/g/$groupSlug/recipes/new': {
      id: '/_app/g/$groupSlug/recipes/new'
      path: '/recipes/new'
      fullPath: '/g/$groupSlug/recipes/new'
      preLoaderRoute: typeof AppGGroupSlugRecipesNewRouteImport
      parentRoute: typeof AppGGroupSlugRoute
    }
    '/_app/g/$groupSlug/nutrition/add': {
      id: '/_app/g/$groupSlug/nutrition/add'
      path: '/add'
      fullPath: '/g/$groupSlug/nutrition/add'
      preLoaderRoute: typeof AppGGroupSlugNutritionAddRouteImport
      parentRoute: typeof AppGGroupSlugNutritionRoute
    }
    '/_app/g/$groupSlug/foods/new': {
      id: '/_app/g/$groupSlug/foods/new'
      path: '/foods/new'
      fullPath: '/g/$groupSlug/foods/new'
      preLoaderRoute: typeof AppGGroupSlugFoodsNewRouteImport
      parentRoute: typeof AppGGroupSlugRoute
    }
    '/_app/g/$groupSlug/baby/new': {
      id: '/_app/g/$groupSlug/baby/new'
      path: '/baby/new'
      fullPath: '/g/$groupSlug/baby/new'
      preLoaderRoute: typeof AppGGroupSlugBabyNewRouteImport
      parentRoute: typeof AppGGroupSlugRoute
    }
    '/_app/g/$groupSlug/recipes/$recipeId/': {
      id: '/_app/g/$groupSlug/recipes/$recipeId/'
      path: '/recipes/$recipeId'
      fullPath: '/g/$groupSlug/recipes/$recipeId/'
      preLoaderRoute: typeof AppGGroupSlugRecipesRecipeIdIndexRouteImport
      parentRoute: typeof AppGGroupSlugRoute
    }
    '/_app/g/$groupSlug/foods/$foodId/': {
      id: '/_app/g/$groupSlug/foods/$foodId/'
      path: '/foods/$foodId'
      fullPath: '/g/$groupSlug/foods/$foodId/'
      preLoaderRoute: typeof AppGGroupSlugFoodsFoodIdIndexRouteImport
      parentRoute: typeof AppGGroupSlugRoute
    }
    '/_app/g/$groupSlug/baby/$babyId/': {
      id: '/_app/g/$groupSlug/baby/$babyId/'
      path: '/baby/$babyId'
      fullPath: '/g/$groupSlug/baby/$babyId/'
      preLoaderRoute: typeof AppGGroupSlugBabyBabyIdIndexRouteImport
      parentRoute: typeof AppGGroupSlugRoute
    }
    '/_app/g/$groupSlug/recipes/$recipeId/edit': {
      id: '/_app/g/$groupSlug/recipes/$recipeId/edit'
      path: '/recipes/$recipeId/edit'
      fullPath: '/g/$groupSlug/recipes/$recipeId/edit'
      preLoaderRoute: typeof AppGGroupSlugRecipesRecipeIdEditRouteImport
      parentRoute: typeof AppGGroupSlugRoute
    }
    '/_app/g/$groupSlug/foods/$foodId/edit': {
      id: '/_app/g/$groupSlug/foods/$foodId/edit'
      path: '/foods/$foodId/edit'
      fullPath: '/g/$groupSlug/foods/$foodId/edit'
      preLoaderRoute: typeof AppGGroupSlugFoodsFoodIdEditRouteImport
      parentRoute: typeof AppGGroupSlugRoute
    }
    '/_app/g/$groupSlug/baby/$babyId/edit': {
      id: '/_app/g/$groupSlug/baby/$babyId/edit'
      path: '/baby/$babyId/edit'
      fullPath: '/g/$groupSlug/baby/$babyId/edit'
      preLoaderRoute: typeof AppGGroupSlugBabyBabyIdEditRouteImport
      parentRoute: typeof AppGGroupSlugRoute
    }
  }
}

interface AppGGroupSlugNutritionRouteChildren {
  AppGGroupSlugNutritionAddRoute: typeof AppGGroupSlugNutritionAddRoute
  AppGGroupSlugNutritionIndexRoute: typeof AppGGroupSlugNutritionIndexRoute
}

const AppGGroupSlugNutritionRouteChildren: AppGGroupSlugNutritionRouteChildren =
  {
    AppGGroupSlugNutritionAddRoute: AppGGroupSlugNutritionAddRoute,
    AppGGroupSlugNutritionIndexRoute: AppGGroupSlugNutritionIndexRoute,
  }

const AppGGroupSlugNutritionRouteWithChildren =
  AppGGroupSlugNutritionRoute._addFileChildren(
    AppGGroupSlugNutritionRouteChildren,
  )

interface AppGGroupSlugRouteChildren {
  AppGGroupSlugAllRoute: typeof AppGGroupSlugAllRoute
  AppGGroupSlugBeersRoute: typeof AppGGroupSlugBeersRoute
  AppGGroupSlugCalendarRoute: typeof AppGGroupSlugCalendarRoute
  AppGGroupSlugCheesesRoute: typeof AppGGroupSlugCheesesRoute
  AppGGroupSlugCombosRoute: typeof AppGGroupSlugCombosRoute
  AppGGroupSlugFinancesRoute: typeof AppGGroupSlugFinancesRoute
  AppGGroupSlugGroceriesRoute: typeof AppGGroupSlugGroceriesRoute
  AppGGroupSlugMealPlannerRoute: typeof AppGGroupSlugMealPlannerRoute
  AppGGroupSlugNotesRoute: typeof AppGGroupSlugNotesRoute
  AppGGroupSlugNutritionRoute: typeof AppGGroupSlugNutritionRouteWithChildren
  AppGGroupSlugPantryRoute: typeof AppGGroupSlugPantryRoute
  AppGGroupSlugSettingsRoute: typeof AppGGroupSlugSettingsRoute
  AppGGroupSlugTasksRoute: typeof AppGGroupSlugTasksRoute
  AppGGroupSlugWinesRoute: typeof AppGGroupSlugWinesRoute
  AppGGroupSlugIndexRoute: typeof AppGGroupSlugIndexRoute
  AppGGroupSlugBabyNewRoute: typeof AppGGroupSlugBabyNewRoute
  AppGGroupSlugFoodsNewRoute: typeof AppGGroupSlugFoodsNewRoute
  AppGGroupSlugRecipesNewRoute: typeof AppGGroupSlugRecipesNewRoute
  AppGGroupSlugBabyIndexRoute: typeof AppGGroupSlugBabyIndexRoute
  AppGGroupSlugFoodsIndexRoute: typeof AppGGroupSlugFoodsIndexRoute
  AppGGroupSlugRecipesIndexRoute: typeof AppGGroupSlugRecipesIndexRoute
  AppGGroupSlugBabyBabyIdEditRoute: typeof AppGGroupSlugBabyBabyIdEditRoute
  AppGGroupSlugFoodsFoodIdEditRoute: typeof AppGGroupSlugFoodsFoodIdEditRoute
  AppGGroupSlugRecipesRecipeIdEditRoute: typeof AppGGroupSlugRecipesRecipeIdEditRoute
  AppGGroupSlugBabyBabyIdIndexRoute: typeof AppGGroupSlugBabyBabyIdIndexRoute
  AppGGroupSlugFoodsFoodIdIndexRoute: typeof AppGGroupSlugFoodsFoodIdIndexRoute
  AppGGroupSlugRecipesRecipeIdIndexRoute: typeof AppGGroupSlugRecipesRecipeIdIndexRoute
}

const AppGGroupSlugRouteChildren: AppGGroupSlugRouteChildren = {
  AppGGroupSlugAllRoute: AppGGroupSlugAllRoute,
  AppGGroupSlugBeersRoute: AppGGroupSlugBeersRoute,
  AppGGroupSlugCalendarRoute: AppGGroupSlugCalendarRoute,
  AppGGroupSlugCheesesRoute: AppGGroupSlugCheesesRoute,
  AppGGroupSlugCombosRoute: AppGGroupSlugCombosRoute,
  AppGGroupSlugFinancesRoute: AppGGroupSlugFinancesRoute,
  AppGGroupSlugGroceriesRoute: AppGGroupSlugGroceriesRoute,
  AppGGroupSlugMealPlannerRoute: AppGGroupSlugMealPlannerRoute,
  AppGGroupSlugNotesRoute: AppGGroupSlugNotesRoute,
  AppGGroupSlugNutritionRoute: AppGGroupSlugNutritionRouteWithChildren,
  AppGGroupSlugPantryRoute: AppGGroupSlugPantryRoute,
  AppGGroupSlugSettingsRoute: AppGGroupSlugSettingsRoute,
  AppGGroupSlugTasksRoute: AppGGroupSlugTasksRoute,
  AppGGroupSlugWinesRoute: AppGGroupSlugWinesRoute,
  AppGGroupSlugIndexRoute: AppGGroupSlugIndexRoute,
  AppGGroupSlugBabyNewRoute: AppGGroupSlugBabyNewRoute,
  AppGGroupSlugFoodsNewRoute: AppGGroupSlugFoodsNewRoute,
  AppGGroupSlugRecipesNewRoute: AppGGroupSlugRecipesNewRoute,
  AppGGroupSlugBabyIndexRoute: AppGGroupSlugBabyIndexRoute,
  AppGGroupSlugFoodsIndexRoute: AppGGroupSlugFoodsIndexRoute,
  AppGGroupSlugRecipesIndexRoute: AppGGroupSlugRecipesIndexRoute,
  AppGGroupSlugBabyBabyIdEditRoute: AppGGroupSlugBabyBabyIdEditRoute,
  AppGGroupSlugFoodsFoodIdEditRoute: AppGGroupSlugFoodsFoodIdEditRoute,
  AppGGroupSlugRecipesRecipeIdEditRoute: AppGGroupSlugRecipesRecipeIdEditRoute,
  AppGGroupSlugBabyBabyIdIndexRoute: AppGGroupSlugBabyBabyIdIndexRoute,
  AppGGroupSlugFoodsFoodIdIndexRoute: AppGGroupSlugFoodsFoodIdIndexRoute,
  AppGGroupSlugRecipesRecipeIdIndexRoute:
    AppGGroupSlugRecipesRecipeIdIndexRoute,
}

const AppGGroupSlugRouteWithChildren = AppGGroupSlugRoute._addFileChildren(
  AppGGroupSlugRouteChildren,
)

interface AppRouteChildren {
  AppSplatRoute: typeof AppSplatRoute
  AppAccountRoute: typeof AppAccountRoute
  AppGroupsRoute: typeof AppGroupsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppGGroupSlugRoute: typeof AppGGroupSlugRouteWithChildren
  AppIntegrationsCallbackRoute: typeof AppIntegrationsCallbackRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSplatRoute: AppSplatRoute,
  AppAccountRoute: AppAccountRoute,
  AppGroupsRoute: AppGroupsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppGGroupSlugRoute: AppGGroupSlugRouteWithChildren,
  AppIntegrationsCallbackRoute: AppIntegrationsCallbackRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AboutRoute: AboutRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
