/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSplatRouteImport } from './routes/_app/$'
import { Route as AppAccountRouteImport } from './routes/_app/account'
import { Route as AppAllRouteImport } from './routes/_app/all'
import { Route as AppBeersRouteImport } from './routes/_app/beers'
import { Route as AppCalendarRouteImport } from './routes/_app/calendar'
import { Route as AppCheesesRouteImport } from './routes/_app/cheeses'
import { Route as AppCombosRouteImport } from './routes/_app/combos'
import { Route as AppFinancesRouteImport } from './routes/_app/finances'
import { Route as AppGroceriesRouteImport } from './routes/_app/groceries'
import { Route as AppGroupSettingsRouteImport } from './routes/_app/group-settings'
import { Route as AppGroupsRouteImport } from './routes/_app/groups'
import { Route as AppHomeRouteImport } from './routes/_app/home'
import { Route as AppMealPlannerRouteImport } from './routes/_app/meal-planner'
import { Route as AppNotesRouteImport } from './routes/_app/notes'
import { Route as AppNutritionRouteImport } from './routes/_app/nutrition'
import { Route as AppPantryRouteImport } from './routes/_app/pantry'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppTasksRouteImport } from './routes/_app/tasks'
import { Route as AppWinesRouteImport } from './routes/_app/wines'
import { Route as AppBabyIndexRouteImport } from './routes/_app/baby/index'
import { Route as AppBabyNewRouteImport } from './routes/_app/baby/new'
import { Route as AppFoodsIndexRouteImport } from './routes/_app/foods/index'
import { Route as AppFoodsNewRouteImport } from './routes/_app/foods/new'
import { Route as AppIntegrationsCallbackRouteImport } from './routes/_app/integrations.callback'
import { Route as AppNutritionIndexRouteImport } from './routes/_app/nutrition/index'
import { Route as AppNutritionAddRouteImport } from './routes/_app/nutrition/add'
import { Route as AppRecipesIndexRouteImport } from './routes/_app/recipes/index'
import { Route as AppRecipesNewRouteImport } from './routes/_app/recipes/new'
import { Route as AppBabyBabyIdIndexRouteImport } from './routes/_app/baby/$babyId.index'
import { Route as AppBabyBabyIdEditRouteImport } from './routes/_app/baby/$babyId.edit'
import { Route as AppFoodsFoodIdIndexRouteImport } from './routes/_app/foods/$foodId.index'
import { Route as AppFoodsFoodIdEditRouteImport } from './routes/_app/foods/$foodId.edit'
import { Route as AppRecipesRecipeIdIndexRouteImport } from './routes/_app/recipes/$recipeId.index'
import { Route as AppRecipesRecipeIdEditRouteImport } from './routes/_app/recipes/$recipeId.edit'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSplatRoute = AppSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppAllRoute = AppAllRouteImport.update({
  id: '/all',
  path: '/all',
  getParentRoute: () => AppRoute,
} as any)
const AppBeersRoute = AppBeersRouteImport.update({
  id: '/beers',
  path: '/beers',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppCheesesRoute = AppCheesesRouteImport.update({
  id: '/cheeses',
  path: '/cheeses',
  getParentRoute: () => AppRoute,
} as any)
const AppCombosRoute = AppCombosRouteImport.update({
  id: '/combos',
  path: '/combos',
  getParentRoute: () => AppRoute,
} as any)
const AppFinancesRoute = AppFinancesRouteImport.update({
  id: '/finances',
  path: '/finances',
  getParentRoute: () => AppRoute,
} as any)
const AppGroceriesRoute = AppGroceriesRouteImport.update({
  id: '/groceries',
  path: '/groceries',
  getParentRoute: () => AppRoute,
} as any)
const AppGroupSettingsRoute = AppGroupSettingsRouteImport.update({
  id: '/group-settings',
  path: '/group-settings',
  getParentRoute: () => AppRoute,
} as any)
const AppGroupsRoute = AppGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppMealPlannerRoute = AppMealPlannerRouteImport.update({
  id: '/meal-planner',
  path: '/meal-planner',
  getParentRoute: () => AppRoute,
} as any)
const AppNotesRoute = AppNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AppRoute,
} as any)
const AppNutritionRoute = AppNutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => AppRoute,
} as any)
const AppPantryRoute = AppPantryRouteImport.update({
  id: '/pantry',
  path: '/pantry',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppWinesRoute = AppWinesRouteImport.update({
  id: '/wines',
  path: '/wines',
  getParentRoute: () => AppRoute,
} as any)
const AppBabyIndexRoute = AppBabyIndexRouteImport.update({
  id: '/baby/',
  path: '/baby/',
  getParentRoute: () => AppRoute,
} as any)
const AppBabyNewRoute = AppBabyNewRouteImport.update({
  id: '/baby/new',
  path: '/baby/new',
  getParentRoute: () => AppRoute,
} as any)
const AppFoodsIndexRoute = AppFoodsIndexRouteImport.update({
  id: '/foods/',
  path: '/foods/',
  getParentRoute: () => AppRoute,
} as any)
const AppFoodsNewRoute = AppFoodsNewRouteImport.update({
  id: '/foods/new',
  path: '/foods/new',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsCallbackRoute = AppIntegrationsCallbackRouteImport.update({
  id: '/integrations/callback',
  path: '/integrations/callback',
  getParentRoute: () => AppRoute,
} as any)
const AppNutritionIndexRoute = AppNutritionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppNutritionRoute,
} as any)
const AppNutritionAddRoute = AppNutritionAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AppNutritionRoute,
} as any)
const AppRecipesIndexRoute = AppRecipesIndexRouteImport.update({
  id: '/recipes/',
  path: '/recipes/',
  getParentRoute: () => AppRoute,
} as any)
const AppRecipesNewRoute = AppRecipesNewRouteImport.update({
  id: '/recipes/new',
  path: '/recipes/new',
  getParentRoute: () => AppRoute,
} as any)
const AppBabyBabyIdIndexRoute = AppBabyBabyIdIndexRouteImport.update({
  id: '/baby/$babyId/',
  path: '/baby/$babyId/',
  getParentRoute: () => AppRoute,
} as any)
const AppBabyBabyIdEditRoute = AppBabyBabyIdEditRouteImport.update({
  id: '/baby/$babyId/edit',
  path: '/baby/$babyId/edit',
  getParentRoute: () => AppRoute,
} as any)
const AppFoodsFoodIdIndexRoute = AppFoodsFoodIdIndexRouteImport.update({
  id: '/foods/$foodId/',
  path: '/foods/$foodId/',
  getParentRoute: () => AppRoute,
} as any)
const AppFoodsFoodIdEditRoute = AppFoodsFoodIdEditRouteImport.update({
  id: '/foods/$foodId/edit',
  path: '/foods/$foodId/edit',
  getParentRoute: () => AppRoute,
} as any)
const AppRecipesRecipeIdIndexRoute = AppRecipesRecipeIdIndexRouteImport.update({
  id: '/recipes/$recipeId/',
  path: '/recipes/$recipeId/',
  getParentRoute: () => AppRoute,
} as any)
const AppRecipesRecipeIdEditRoute = AppRecipesRecipeIdEditRouteImport.update({
  id: '/recipes/$recipeId/edit',
  path: '/recipes/$recipeId/edit',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/about': typeof AboutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/$': typeof AppSplatRoute
  '/account': typeof AppAccountRoute
  '/all': typeof AppAllRoute
  '/beers': typeof AppBeersRoute
  '/calendar': typeof AppCalendarRoute
  '/cheeses': typeof AppCheesesRoute
  '/combos': typeof AppCombosRoute
  '/finances': typeof AppFinancesRoute
  '/groceries': typeof AppGroceriesRoute
  '/group-settings': typeof AppGroupSettingsRoute
  '/groups': typeof AppGroupsRoute
  '/home': typeof AppHomeRoute
  '/meal-planner': typeof AppMealPlannerRoute
  '/notes': typeof AppNotesRoute
  '/nutrition': typeof AppNutritionRouteWithChildren
  '/pantry': typeof AppPantryRoute
  '/settings': typeof AppSettingsRoute
  '/tasks': typeof AppTasksRoute
  '/wines': typeof AppWinesRoute
  '/baby/new': typeof AppBabyNewRoute
  '/foods/new': typeof AppFoodsNewRoute
  '/integrations/callback': typeof AppIntegrationsCallbackRoute
  '/nutrition/add': typeof AppNutritionAddRoute
  '/recipes/new': typeof AppRecipesNewRoute
  '/baby/': typeof AppBabyIndexRoute
  '/foods/': typeof AppFoodsIndexRoute
  '/nutrition/': typeof AppNutritionIndexRoute
  '/recipes/': typeof AppRecipesIndexRoute
  '/baby/$babyId/edit': typeof AppBabyBabyIdEditRoute
  '/foods/$foodId/edit': typeof AppFoodsFoodIdEditRoute
  '/recipes/$recipeId/edit': typeof AppRecipesRecipeIdEditRoute
  '/baby/$babyId/': typeof AppBabyBabyIdIndexRoute
  '/foods/$foodId/': typeof AppFoodsFoodIdIndexRoute
  '/recipes/$recipeId/': typeof AppRecipesRecipeIdIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof AboutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/$': typeof AppSplatRoute
  '/account': typeof AppAccountRoute
  '/all': typeof AppAllRoute
  '/beers': typeof AppBeersRoute
  '/calendar': typeof AppCalendarRoute
  '/cheeses': typeof AppCheesesRoute
  '/combos': typeof AppCombosRoute
  '/finances': typeof AppFinancesRoute
  '/groceries': typeof AppGroceriesRoute
  '/group-settings': typeof AppGroupSettingsRoute
  '/groups': typeof AppGroupsRoute
  '/home': typeof AppHomeRoute
  '/meal-planner': typeof AppMealPlannerRoute
  '/notes': typeof AppNotesRoute
  '/pantry': typeof AppPantryRoute
  '/settings': typeof AppSettingsRoute
  '/tasks': typeof AppTasksRoute
  '/wines': typeof AppWinesRoute
  '/': typeof AppIndexRoute
  '/baby/new': typeof AppBabyNewRoute
  '/foods/new': typeof AppFoodsNewRoute
  '/integrations/callback': typeof AppIntegrationsCallbackRoute
  '/nutrition/add': typeof AppNutritionAddRoute
  '/recipes/new': typeof AppRecipesNewRoute
  '/baby': typeof AppBabyIndexRoute
  '/foods': typeof AppFoodsIndexRoute
  '/nutrition': typeof AppNutritionIndexRoute
  '/recipes': typeof AppRecipesIndexRoute
  '/baby/$babyId/edit': typeof AppBabyBabyIdEditRoute
  '/foods/$foodId/edit': typeof AppFoodsFoodIdEditRoute
  '/recipes/$recipeId/edit': typeof AppRecipesRecipeIdEditRoute
  '/baby/$babyId': typeof AppBabyBabyIdIndexRoute
  '/foods/$foodId': typeof AppFoodsFoodIdIndexRoute
  '/recipes/$recipeId': typeof AppRecipesRecipeIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/about': typeof AboutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_app/$': typeof AppSplatRoute
  '/_app/account': typeof AppAccountRoute
  '/_app/all': typeof AppAllRoute
  '/_app/beers': typeof AppBeersRoute
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/cheeses': typeof AppCheesesRoute
  '/_app/combos': typeof AppCombosRoute
  '/_app/finances': typeof AppFinancesRoute
  '/_app/groceries': typeof AppGroceriesRoute
  '/_app/group-settings': typeof AppGroupSettingsRoute
  '/_app/groups': typeof AppGroupsRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/meal-planner': typeof AppMealPlannerRoute
  '/_app/notes': typeof AppNotesRoute
  '/_app/nutrition': typeof AppNutritionRouteWithChildren
  '/_app/pantry': typeof AppPantryRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/tasks': typeof AppTasksRoute
  '/_app/wines': typeof AppWinesRoute
  '/_app/': typeof AppIndexRoute
  '/_app/baby/new': typeof AppBabyNewRoute
  '/_app/foods/new': typeof AppFoodsNewRoute
  '/_app/integrations/callback': typeof AppIntegrationsCallbackRoute
  '/_app/nutrition/add': typeof AppNutritionAddRoute
  '/_app/recipes/new': typeof AppRecipesNewRoute
  '/_app/baby/': typeof AppBabyIndexRoute
  '/_app/foods/': typeof AppFoodsIndexRoute
  '/_app/nutrition/': typeof AppNutritionIndexRoute
  '/_app/recipes/': typeof AppRecipesIndexRoute
  '/_app/baby/$babyId/edit': typeof AppBabyBabyIdEditRoute
  '/_app/foods/$foodId/edit': typeof AppFoodsFoodIdEditRoute
  '/_app/recipes/$recipeId/edit': typeof AppRecipesRecipeIdEditRoute
  '/_app/baby/$babyId/': typeof AppBabyBabyIdIndexRoute
  '/_app/foods/$foodId/': typeof AppFoodsFoodIdIndexRoute
  '/_app/recipes/$recipeId/': typeof AppRecipesRecipeIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/$'
    | '/account'
    | '/all'
    | '/beers'
    | '/calendar'
    | '/cheeses'
    | '/combos'
    | '/finances'
    | '/groceries'
    | '/group-settings'
    | '/groups'
    | '/home'
    | '/meal-planner'
    | '/notes'
    | '/nutrition'
    | '/pantry'
    | '/settings'
    | '/tasks'
    | '/wines'
    | '/baby/new'
    | '/foods/new'
    | '/integrations/callback'
    | '/nutrition/add'
    | '/recipes/new'
    | '/baby/'
    | '/foods/'
    | '/nutrition/'
    | '/recipes/'
    | '/baby/$babyId/edit'
    | '/foods/$foodId/edit'
    | '/recipes/$recipeId/edit'
    | '/baby/$babyId/'
    | '/foods/$foodId/'
    | '/recipes/$recipeId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/$'
    | '/account'
    | '/all'
    | '/beers'
    | '/calendar'
    | '/cheeses'
    | '/combos'
    | '/finances'
    | '/groceries'
    | '/group-settings'
    | '/groups'
    | '/home'
    | '/meal-planner'
    | '/notes'
    | '/pantry'
    | '/settings'
    | '/tasks'
    | '/wines'
    | '/'
    | '/baby/new'
    | '/foods/new'
    | '/integrations/callback'
    | '/nutrition/add'
    | '/recipes/new'
    | '/baby'
    | '/foods'
    | '/nutrition'
    | '/recipes'
    | '/baby/$babyId/edit'
    | '/foods/$foodId/edit'
    | '/recipes/$recipeId/edit'
    | '/baby/$babyId'
    | '/foods/$foodId'
    | '/recipes/$recipeId'
  id:
    | '__root__'
    | '/_app'
    | '/about'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/_app/$'
    | '/_app/account'
    | '/_app/all'
    | '/_app/beers'
    | '/_app/calendar'
    | '/_app/cheeses'
    | '/_app/combos'
    | '/_app/finances'
    | '/_app/groceries'
    | '/_app/group-settings'
    | '/_app/groups'
    | '/_app/home'
    | '/_app/meal-planner'
    | '/_app/notes'
    | '/_app/nutrition'
    | '/_app/pantry'
    | '/_app/settings'
    | '/_app/tasks'
    | '/_app/wines'
    | '/_app/'
    | '/_app/baby/new'
    | '/_app/foods/new'
    | '/_app/integrations/callback'
    | '/_app/nutrition/add'
    | '/_app/recipes/new'
    | '/_app/baby/'
    | '/_app/foods/'
    | '/_app/nutrition/'
    | '/_app/recipes/'
    | '/_app/baby/$babyId/edit'
    | '/_app/foods/$foodId/edit'
    | '/_app/recipes/$recipeId/edit'
    | '/_app/baby/$babyId/'
    | '/_app/foods/$foodId/'
    | '/_app/recipes/$recipeId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AboutRoute: typeof AboutRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$': {
      id: '/_app/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof AppSplatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/all': {
      id: '/_app/all'
      path: '/all'
      fullPath: '/all'
      preLoaderRoute: typeof AppAllRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/beers': {
      id: '/_app/beers'
      path: '/beers'
      fullPath: '/beers'
      preLoaderRoute: typeof AppBeersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cheeses': {
      id: '/_app/cheeses'
      path: '/cheeses'
      fullPath: '/cheeses'
      preLoaderRoute: typeof AppCheesesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/combos': {
      id: '/_app/combos'
      path: '/combos'
      fullPath: '/combos'
      preLoaderRoute: typeof AppCombosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finances': {
      id: '/_app/finances'
      path: '/finances'
      fullPath: '/finances'
      preLoaderRoute: typeof AppFinancesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/groceries': {
      id: '/_app/groceries'
      path: '/groceries'
      fullPath: '/groceries'
      preLoaderRoute: typeof AppGroceriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/group-settings': {
      id: '/_app/group-settings'
      path: '/group-settings'
      fullPath: '/group-settings'
      preLoaderRoute: typeof AppGroupSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/groups': {
      id: '/_app/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof AppGroupsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/meal-planner': {
      id: '/_app/meal-planner'
      path: '/meal-planner'
      fullPath: '/meal-planner'
      preLoaderRoute: typeof AppMealPlannerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notes': {
      id: '/_app/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AppNotesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/nutrition': {
      id: '/_app/nutrition'
      path: '/nutrition'
      fullPath: '/nutrition'
      preLoaderRoute: typeof AppNutritionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pantry': {
      id: '/_app/pantry'
      path: '/pantry'
      fullPath: '/pantry'
      preLoaderRoute: typeof AppPantryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/wines': {
      id: '/_app/wines'
      path: '/wines'
      fullPath: '/wines'
      preLoaderRoute: typeof AppWinesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/baby/': {
      id: '/_app/baby/'
      path: '/baby'
      fullPath: '/baby/'
      preLoaderRoute: typeof AppBabyIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/baby/new': {
      id: '/_app/baby/new'
      path: '/baby/new'
      fullPath: '/baby/new'
      preLoaderRoute: typeof AppBabyNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/foods/': {
      id: '/_app/foods/'
      path: '/foods'
      fullPath: '/foods/'
      preLoaderRoute: typeof AppFoodsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/foods/new': {
      id: '/_app/foods/new'
      path: '/foods/new'
      fullPath: '/foods/new'
      preLoaderRoute: typeof AppFoodsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integrations/callback': {
      id: '/_app/integrations/callback'
      path: '/integrations/callback'
      fullPath: '/integrations/callback'
      preLoaderRoute: typeof AppIntegrationsCallbackRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/nutrition/': {
      id: '/_app/nutrition/'
      path: '/'
      fullPath: '/nutrition/'
      preLoaderRoute: typeof AppNutritionIndexRouteImport
      parentRoute: typeof AppNutritionRoute
    }
    '/_app/nutrition/add': {
      id: '/_app/nutrition/add'
      path: '/add'
      fullPath: '/nutrition/add'
      preLoaderRoute: typeof AppNutritionAddRouteImport
      parentRoute: typeof AppNutritionRoute
    }
    '/_app/recipes/': {
      id: '/_app/recipes/'
      path: '/recipes'
      fullPath: '/recipes/'
      preLoaderRoute: typeof AppRecipesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recipes/new': {
      id: '/_app/recipes/new'
      path: '/recipes/new'
      fullPath: '/recipes/new'
      preLoaderRoute: typeof AppRecipesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/baby/$babyId/': {
      id: '/_app/baby/$babyId/'
      path: '/baby/$babyId'
      fullPath: '/baby/$babyId/'
      preLoaderRoute: typeof AppBabyBabyIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/baby/$babyId/edit': {
      id: '/_app/baby/$babyId/edit'
      path: '/baby/$babyId/edit'
      fullPath: '/baby/$babyId/edit'
      preLoaderRoute: typeof AppBabyBabyIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/foods/$foodId/': {
      id: '/_app/foods/$foodId/'
      path: '/foods/$foodId'
      fullPath: '/foods/$foodId/'
      preLoaderRoute: typeof AppFoodsFoodIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/foods/$foodId/edit': {
      id: '/_app/foods/$foodId/edit'
      path: '/foods/$foodId/edit'
      fullPath: '/foods/$foodId/edit'
      preLoaderRoute: typeof AppFoodsFoodIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recipes/$recipeId/': {
      id: '/_app/recipes/$recipeId/'
      path: '/recipes/$recipeId'
      fullPath: '/recipes/$recipeId/'
      preLoaderRoute: typeof AppRecipesRecipeIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recipes/$recipeId/edit': {
      id: '/_app/recipes/$recipeId/edit'
      path: '/recipes/$recipeId/edit'
      fullPath: '/recipes/$recipeId/edit'
      preLoaderRoute: typeof AppRecipesRecipeIdEditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppNutritionRouteChildren {
  AppNutritionAddRoute: typeof AppNutritionAddRoute
  AppNutritionIndexRoute: typeof AppNutritionIndexRoute
}

const AppNutritionRouteChildren: AppNutritionRouteChildren = {
  AppNutritionAddRoute: AppNutritionAddRoute,
  AppNutritionIndexRoute: AppNutritionIndexRoute,
}

const AppNutritionRouteWithChildren = AppNutritionRoute._addFileChildren(
  AppNutritionRouteChildren,
)

interface AppRouteChildren {
  AppSplatRoute: typeof AppSplatRoute
  AppAccountRoute: typeof AppAccountRoute
  AppAllRoute: typeof AppAllRoute
  AppBeersRoute: typeof AppBeersRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppCheesesRoute: typeof AppCheesesRoute
  AppCombosRoute: typeof AppCombosRoute
  AppFinancesRoute: typeof AppFinancesRoute
  AppGroceriesRoute: typeof AppGroceriesRoute
  AppGroupSettingsRoute: typeof AppGroupSettingsRoute
  AppGroupsRoute: typeof AppGroupsRoute
  AppHomeRoute: typeof AppHomeRoute
  AppMealPlannerRoute: typeof AppMealPlannerRoute
  AppNotesRoute: typeof AppNotesRoute
  AppNutritionRoute: typeof AppNutritionRouteWithChildren
  AppPantryRoute: typeof AppPantryRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTasksRoute: typeof AppTasksRoute
  AppWinesRoute: typeof AppWinesRoute
  AppIndexRoute: typeof AppIndexRoute
  AppBabyNewRoute: typeof AppBabyNewRoute
  AppFoodsNewRoute: typeof AppFoodsNewRoute
  AppIntegrationsCallbackRoute: typeof AppIntegrationsCallbackRoute
  AppRecipesNewRoute: typeof AppRecipesNewRoute
  AppBabyIndexRoute: typeof AppBabyIndexRoute
  AppFoodsIndexRoute: typeof AppFoodsIndexRoute
  AppRecipesIndexRoute: typeof AppRecipesIndexRoute
  AppBabyBabyIdEditRoute: typeof AppBabyBabyIdEditRoute
  AppFoodsFoodIdEditRoute: typeof AppFoodsFoodIdEditRoute
  AppRecipesRecipeIdEditRoute: typeof AppRecipesRecipeIdEditRoute
  AppBabyBabyIdIndexRoute: typeof AppBabyBabyIdIndexRoute
  AppFoodsFoodIdIndexRoute: typeof AppFoodsFoodIdIndexRoute
  AppRecipesRecipeIdIndexRoute: typeof AppRecipesRecipeIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSplatRoute: AppSplatRoute,
  AppAccountRoute: AppAccountRoute,
  AppAllRoute: AppAllRoute,
  AppBeersRoute: AppBeersRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppCheesesRoute: AppCheesesRoute,
  AppCombosRoute: AppCombosRoute,
  AppFinancesRoute: AppFinancesRoute,
  AppGroceriesRoute: AppGroceriesRoute,
  AppGroupSettingsRoute: AppGroupSettingsRoute,
  AppGroupsRoute: AppGroupsRoute,
  AppHomeRoute: AppHomeRoute,
  AppMealPlannerRoute: AppMealPlannerRoute,
  AppNotesRoute: AppNotesRoute,
  AppNutritionRoute: AppNutritionRouteWithChildren,
  AppPantryRoute: AppPantryRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTasksRoute: AppTasksRoute,
  AppWinesRoute: AppWinesRoute,
  AppIndexRoute: AppIndexRoute,
  AppBabyNewRoute: AppBabyNewRoute,
  AppFoodsNewRoute: AppFoodsNewRoute,
  AppIntegrationsCallbackRoute: AppIntegrationsCallbackRoute,
  AppRecipesNewRoute: AppRecipesNewRoute,
  AppBabyIndexRoute: AppBabyIndexRoute,
  AppFoodsIndexRoute: AppFoodsIndexRoute,
  AppRecipesIndexRoute: AppRecipesIndexRoute,
  AppBabyBabyIdEditRoute: AppBabyBabyIdEditRoute,
  AppFoodsFoodIdEditRoute: AppFoodsFoodIdEditRoute,
  AppRecipesRecipeIdEditRoute: AppRecipesRecipeIdEditRoute,
  AppBabyBabyIdIndexRoute: AppBabyBabyIdIndexRoute,
  AppFoodsFoodIdIndexRoute: AppFoodsFoodIdIndexRoute,
  AppRecipesRecipeIdIndexRoute: AppRecipesRecipeIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AboutRoute: AboutRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
