/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWinesRouteImport } from './routes/_app/wines'
import { Route as AppTasksRouteImport } from './routes/_app/tasks'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppPantryRouteImport } from './routes/_app/pantry'
import { Route as AppOnboardingRouteImport } from './routes/_app/onboarding'
import { Route as AppNotesRouteImport } from './routes/_app/notes'
import { Route as AppMealPlannerRouteImport } from './routes/_app/meal-planner'
import { Route as AppGroceriesRouteImport } from './routes/_app/groceries'
import { Route as AppFinancesRouteImport } from './routes/_app/finances'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCheesesRouteImport } from './routes/_app/cheeses'
import { Route as AppCalendarRouteImport } from './routes/_app/calendar'
import { Route as AppBillsRouteImport } from './routes/_app/bills'
import { Route as AppAccountRouteImport } from './routes/_app/account'
import { Route as AppNutritionIndexRouteImport } from './routes/_app/nutrition/index'
import { Route as AppFoodsIndexRouteImport } from './routes/_app/foods/index'
import { Route as AppSSpaceSlugRouteImport } from './routes/_app/s/$spaceSlug'
import { Route as AppIntegrationsCallbackRouteImport } from './routes/_app/integrations.callback'
import { Route as AppFoodsNewRouteImport } from './routes/_app/foods/new'
import { Route as AppSSpaceSlugIndexRouteImport } from './routes/_app/s/$spaceSlug/index'
import { Route as AppFoodsFoodIdIndexRouteImport } from './routes/_app/foods/$foodId.index'
import { Route as AppSSpaceSlugSettingsRouteImport } from './routes/_app/s/$spaceSlug/settings'
import { Route as AppSSpaceSlugModulesRouteImport } from './routes/_app/s/$spaceSlug/modules'
import { Route as AppSSpaceSlugMembersRouteImport } from './routes/_app/s/$spaceSlug/members'
import { Route as AppSSpaceSlugHomeRouteImport } from './routes/_app/s/$spaceSlug/home'
import { Route as AppFoodsFoodIdEditRouteImport } from './routes/_app/foods/$foodId.edit'
import { Route as AppSSpaceSlugSettingsIndexRouteImport } from './routes/_app/s/$spaceSlug/settings/index'
import { Route as AppSSpaceSlugRecipesIndexRouteImport } from './routes/_app/s/$spaceSlug/recipes/index'
import { Route as AppSSpaceSlugNutritionIndexRouteImport } from './routes/_app/s/$spaceSlug/nutrition/index'
import { Route as AppSSpaceSlugSettingsNavigationRouteImport } from './routes/_app/s/$spaceSlug/settings/navigation'
import { Route as AppSSpaceSlugSettingsModulesRouteImport } from './routes/_app/s/$spaceSlug/settings/modules'
import { Route as AppSSpaceSlugSettingsDashboardRouteImport } from './routes/_app/s/$spaceSlug/settings/dashboard'
import { Route as AppSSpaceSlugRecipesNewRouteImport } from './routes/_app/s/$spaceSlug/recipes/new'
import { Route as AppSSpaceSlugRecipesRecipeIdIndexRouteImport } from './routes/_app/s/$spaceSlug/recipes/$recipeId.index'
import { Route as AppSSpaceSlugRecipesRecipeIdEditRouteImport } from './routes/_app/s/$spaceSlug/recipes/$recipeId.edit'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWinesRoute = AppWinesRouteImport.update({
  id: '/wines',
  path: '/wines',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPantryRoute = AppPantryRouteImport.update({
  id: '/pantry',
  path: '/pantry',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppNotesRoute = AppNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AppRoute,
} as any)
const AppMealPlannerRoute = AppMealPlannerRouteImport.update({
  id: '/meal-planner',
  path: '/meal-planner',
  getParentRoute: () => AppRoute,
} as any)
const AppGroceriesRoute = AppGroceriesRouteImport.update({
  id: '/groceries',
  path: '/groceries',
  getParentRoute: () => AppRoute,
} as any)
const AppFinancesRoute = AppFinancesRouteImport.update({
  id: '/finances',
  path: '/finances',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCheesesRoute = AppCheesesRouteImport.update({
  id: '/cheeses',
  path: '/cheeses',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppBillsRoute = AppBillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppNutritionIndexRoute = AppNutritionIndexRouteImport.update({
  id: '/nutrition/',
  path: '/nutrition/',
  getParentRoute: () => AppRoute,
} as any)
const AppFoodsIndexRoute = AppFoodsIndexRouteImport.update({
  id: '/foods/',
  path: '/foods/',
  getParentRoute: () => AppRoute,
} as any)
const AppSSpaceSlugRoute = AppSSpaceSlugRouteImport.update({
  id: '/s/$spaceSlug',
  path: '/s/$spaceSlug',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsCallbackRoute = AppIntegrationsCallbackRouteImport.update({
  id: '/integrations/callback',
  path: '/integrations/callback',
  getParentRoute: () => AppRoute,
} as any)
const AppFoodsNewRoute = AppFoodsNewRouteImport.update({
  id: '/foods/new',
  path: '/foods/new',
  getParentRoute: () => AppRoute,
} as any)
const AppSSpaceSlugIndexRoute = AppSSpaceSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSSpaceSlugRoute,
} as any)
const AppFoodsFoodIdIndexRoute = AppFoodsFoodIdIndexRouteImport.update({
  id: '/foods/$foodId/',
  path: '/foods/$foodId/',
  getParentRoute: () => AppRoute,
} as any)
const AppSSpaceSlugSettingsRoute = AppSSpaceSlugSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppSSpaceSlugRoute,
} as any)
const AppSSpaceSlugModulesRoute = AppSSpaceSlugModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => AppSSpaceSlugRoute,
} as any)
const AppSSpaceSlugMembersRoute = AppSSpaceSlugMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppSSpaceSlugRoute,
} as any)
const AppSSpaceSlugHomeRoute = AppSSpaceSlugHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppSSpaceSlugRoute,
} as any)
const AppFoodsFoodIdEditRoute = AppFoodsFoodIdEditRouteImport.update({
  id: '/foods/$foodId/edit',
  path: '/foods/$foodId/edit',
  getParentRoute: () => AppRoute,
} as any)
const AppSSpaceSlugSettingsIndexRoute =
  AppSSpaceSlugSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppSSpaceSlugSettingsRoute,
  } as any)
const AppSSpaceSlugRecipesIndexRoute =
  AppSSpaceSlugRecipesIndexRouteImport.update({
    id: '/recipes/',
    path: '/recipes/',
    getParentRoute: () => AppSSpaceSlugRoute,
  } as any)
const AppSSpaceSlugNutritionIndexRoute =
  AppSSpaceSlugNutritionIndexRouteImport.update({
    id: '/nutrition/',
    path: '/nutrition/',
    getParentRoute: () => AppSSpaceSlugRoute,
  } as any)
const AppSSpaceSlugSettingsNavigationRoute =
  AppSSpaceSlugSettingsNavigationRouteImport.update({
    id: '/navigation',
    path: '/navigation',
    getParentRoute: () => AppSSpaceSlugSettingsRoute,
  } as any)
const AppSSpaceSlugSettingsModulesRoute =
  AppSSpaceSlugSettingsModulesRouteImport.update({
    id: '/modules',
    path: '/modules',
    getParentRoute: () => AppSSpaceSlugSettingsRoute,
  } as any)
const AppSSpaceSlugSettingsDashboardRoute =
  AppSSpaceSlugSettingsDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AppSSpaceSlugSettingsRoute,
  } as any)
const AppSSpaceSlugRecipesNewRoute = AppSSpaceSlugRecipesNewRouteImport.update({
  id: '/recipes/new',
  path: '/recipes/new',
  getParentRoute: () => AppSSpaceSlugRoute,
} as any)
const AppSSpaceSlugRecipesRecipeIdIndexRoute =
  AppSSpaceSlugRecipesRecipeIdIndexRouteImport.update({
    id: '/recipes/$recipeId/',
    path: '/recipes/$recipeId/',
    getParentRoute: () => AppSSpaceSlugRoute,
  } as any)
const AppSSpaceSlugRecipesRecipeIdEditRoute =
  AppSSpaceSlugRecipesRecipeIdEditRouteImport.update({
    id: '/recipes/$recipeId/edit',
    path: '/recipes/$recipeId/edit',
    getParentRoute: () => AppSSpaceSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/account': typeof AppAccountRoute
  '/bills': typeof AppBillsRoute
  '/calendar': typeof AppCalendarRoute
  '/cheeses': typeof AppCheesesRoute
  '/dashboard': typeof AppDashboardRoute
  '/finances': typeof AppFinancesRoute
  '/groceries': typeof AppGroceriesRoute
  '/meal-planner': typeof AppMealPlannerRoute
  '/notes': typeof AppNotesRoute
  '/onboarding': typeof AppOnboardingRoute
  '/pantry': typeof AppPantryRoute
  '/settings': typeof AppSettingsRoute
  '/tasks': typeof AppTasksRoute
  '/wines': typeof AppWinesRoute
  '/foods/new': typeof AppFoodsNewRoute
  '/integrations/callback': typeof AppIntegrationsCallbackRoute
  '/s/$spaceSlug': typeof AppSSpaceSlugRouteWithChildren
  '/foods/': typeof AppFoodsIndexRoute
  '/nutrition/': typeof AppNutritionIndexRoute
  '/foods/$foodId/edit': typeof AppFoodsFoodIdEditRoute
  '/s/$spaceSlug/home': typeof AppSSpaceSlugHomeRoute
  '/s/$spaceSlug/members': typeof AppSSpaceSlugMembersRoute
  '/s/$spaceSlug/modules': typeof AppSSpaceSlugModulesRoute
  '/s/$spaceSlug/settings': typeof AppSSpaceSlugSettingsRouteWithChildren
  '/foods/$foodId/': typeof AppFoodsFoodIdIndexRoute
  '/s/$spaceSlug/': typeof AppSSpaceSlugIndexRoute
  '/s/$spaceSlug/recipes/new': typeof AppSSpaceSlugRecipesNewRoute
  '/s/$spaceSlug/settings/dashboard': typeof AppSSpaceSlugSettingsDashboardRoute
  '/s/$spaceSlug/settings/modules': typeof AppSSpaceSlugSettingsModulesRoute
  '/s/$spaceSlug/settings/navigation': typeof AppSSpaceSlugSettingsNavigationRoute
  '/s/$spaceSlug/nutrition/': typeof AppSSpaceSlugNutritionIndexRoute
  '/s/$spaceSlug/recipes/': typeof AppSSpaceSlugRecipesIndexRoute
  '/s/$spaceSlug/settings/': typeof AppSSpaceSlugSettingsIndexRoute
  '/s/$spaceSlug/recipes/$recipeId/edit': typeof AppSSpaceSlugRecipesRecipeIdEditRoute
  '/s/$spaceSlug/recipes/$recipeId/': typeof AppSSpaceSlugRecipesRecipeIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/account': typeof AppAccountRoute
  '/bills': typeof AppBillsRoute
  '/calendar': typeof AppCalendarRoute
  '/cheeses': typeof AppCheesesRoute
  '/dashboard': typeof AppDashboardRoute
  '/finances': typeof AppFinancesRoute
  '/groceries': typeof AppGroceriesRoute
  '/meal-planner': typeof AppMealPlannerRoute
  '/notes': typeof AppNotesRoute
  '/onboarding': typeof AppOnboardingRoute
  '/pantry': typeof AppPantryRoute
  '/settings': typeof AppSettingsRoute
  '/tasks': typeof AppTasksRoute
  '/wines': typeof AppWinesRoute
  '/foods/new': typeof AppFoodsNewRoute
  '/integrations/callback': typeof AppIntegrationsCallbackRoute
  '/foods': typeof AppFoodsIndexRoute
  '/nutrition': typeof AppNutritionIndexRoute
  '/foods/$foodId/edit': typeof AppFoodsFoodIdEditRoute
  '/s/$spaceSlug/home': typeof AppSSpaceSlugHomeRoute
  '/s/$spaceSlug/members': typeof AppSSpaceSlugMembersRoute
  '/s/$spaceSlug/modules': typeof AppSSpaceSlugModulesRoute
  '/foods/$foodId': typeof AppFoodsFoodIdIndexRoute
  '/s/$spaceSlug': typeof AppSSpaceSlugIndexRoute
  '/s/$spaceSlug/recipes/new': typeof AppSSpaceSlugRecipesNewRoute
  '/s/$spaceSlug/settings/dashboard': typeof AppSSpaceSlugSettingsDashboardRoute
  '/s/$spaceSlug/settings/modules': typeof AppSSpaceSlugSettingsModulesRoute
  '/s/$spaceSlug/settings/navigation': typeof AppSSpaceSlugSettingsNavigationRoute
  '/s/$spaceSlug/nutrition': typeof AppSSpaceSlugNutritionIndexRoute
  '/s/$spaceSlug/recipes': typeof AppSSpaceSlugRecipesIndexRoute
  '/s/$spaceSlug/settings': typeof AppSSpaceSlugSettingsIndexRoute
  '/s/$spaceSlug/recipes/$recipeId/edit': typeof AppSSpaceSlugRecipesRecipeIdEditRoute
  '/s/$spaceSlug/recipes/$recipeId': typeof AppSSpaceSlugRecipesRecipeIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/about': typeof AboutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_app/account': typeof AppAccountRoute
  '/_app/bills': typeof AppBillsRoute
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/cheeses': typeof AppCheesesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/finances': typeof AppFinancesRoute
  '/_app/groceries': typeof AppGroceriesRoute
  '/_app/meal-planner': typeof AppMealPlannerRoute
  '/_app/notes': typeof AppNotesRoute
  '/_app/onboarding': typeof AppOnboardingRoute
  '/_app/pantry': typeof AppPantryRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/tasks': typeof AppTasksRoute
  '/_app/wines': typeof AppWinesRoute
  '/_app/foods/new': typeof AppFoodsNewRoute
  '/_app/integrations/callback': typeof AppIntegrationsCallbackRoute
  '/_app/s/$spaceSlug': typeof AppSSpaceSlugRouteWithChildren
  '/_app/foods/': typeof AppFoodsIndexRoute
  '/_app/nutrition/': typeof AppNutritionIndexRoute
  '/_app/foods/$foodId/edit': typeof AppFoodsFoodIdEditRoute
  '/_app/s/$spaceSlug/home': typeof AppSSpaceSlugHomeRoute
  '/_app/s/$spaceSlug/members': typeof AppSSpaceSlugMembersRoute
  '/_app/s/$spaceSlug/modules': typeof AppSSpaceSlugModulesRoute
  '/_app/s/$spaceSlug/settings': typeof AppSSpaceSlugSettingsRouteWithChildren
  '/_app/foods/$foodId/': typeof AppFoodsFoodIdIndexRoute
  '/_app/s/$spaceSlug/': typeof AppSSpaceSlugIndexRoute
  '/_app/s/$spaceSlug/recipes/new': typeof AppSSpaceSlugRecipesNewRoute
  '/_app/s/$spaceSlug/settings/dashboard': typeof AppSSpaceSlugSettingsDashboardRoute
  '/_app/s/$spaceSlug/settings/modules': typeof AppSSpaceSlugSettingsModulesRoute
  '/_app/s/$spaceSlug/settings/navigation': typeof AppSSpaceSlugSettingsNavigationRoute
  '/_app/s/$spaceSlug/nutrition/': typeof AppSSpaceSlugNutritionIndexRoute
  '/_app/s/$spaceSlug/recipes/': typeof AppSSpaceSlugRecipesIndexRoute
  '/_app/s/$spaceSlug/settings/': typeof AppSSpaceSlugSettingsIndexRoute
  '/_app/s/$spaceSlug/recipes/$recipeId/edit': typeof AppSSpaceSlugRecipesRecipeIdEditRoute
  '/_app/s/$spaceSlug/recipes/$recipeId/': typeof AppSSpaceSlugRecipesRecipeIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/account'
    | '/bills'
    | '/calendar'
    | '/cheeses'
    | '/dashboard'
    | '/finances'
    | '/groceries'
    | '/meal-planner'
    | '/notes'
    | '/onboarding'
    | '/pantry'
    | '/settings'
    | '/tasks'
    | '/wines'
    | '/foods/new'
    | '/integrations/callback'
    | '/s/$spaceSlug'
    | '/foods/'
    | '/nutrition/'
    | '/foods/$foodId/edit'
    | '/s/$spaceSlug/home'
    | '/s/$spaceSlug/members'
    | '/s/$spaceSlug/modules'
    | '/s/$spaceSlug/settings'
    | '/foods/$foodId/'
    | '/s/$spaceSlug/'
    | '/s/$spaceSlug/recipes/new'
    | '/s/$spaceSlug/settings/dashboard'
    | '/s/$spaceSlug/settings/modules'
    | '/s/$spaceSlug/settings/navigation'
    | '/s/$spaceSlug/nutrition/'
    | '/s/$spaceSlug/recipes/'
    | '/s/$spaceSlug/settings/'
    | '/s/$spaceSlug/recipes/$recipeId/edit'
    | '/s/$spaceSlug/recipes/$recipeId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/account'
    | '/bills'
    | '/calendar'
    | '/cheeses'
    | '/dashboard'
    | '/finances'
    | '/groceries'
    | '/meal-planner'
    | '/notes'
    | '/onboarding'
    | '/pantry'
    | '/settings'
    | '/tasks'
    | '/wines'
    | '/foods/new'
    | '/integrations/callback'
    | '/foods'
    | '/nutrition'
    | '/foods/$foodId/edit'
    | '/s/$spaceSlug/home'
    | '/s/$spaceSlug/members'
    | '/s/$spaceSlug/modules'
    | '/foods/$foodId'
    | '/s/$spaceSlug'
    | '/s/$spaceSlug/recipes/new'
    | '/s/$spaceSlug/settings/dashboard'
    | '/s/$spaceSlug/settings/modules'
    | '/s/$spaceSlug/settings/navigation'
    | '/s/$spaceSlug/nutrition'
    | '/s/$spaceSlug/recipes'
    | '/s/$spaceSlug/settings'
    | '/s/$spaceSlug/recipes/$recipeId/edit'
    | '/s/$spaceSlug/recipes/$recipeId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/about'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/_app/account'
    | '/_app/bills'
    | '/_app/calendar'
    | '/_app/cheeses'
    | '/_app/dashboard'
    | '/_app/finances'
    | '/_app/groceries'
    | '/_app/meal-planner'
    | '/_app/notes'
    | '/_app/onboarding'
    | '/_app/pantry'
    | '/_app/settings'
    | '/_app/tasks'
    | '/_app/wines'
    | '/_app/foods/new'
    | '/_app/integrations/callback'
    | '/_app/s/$spaceSlug'
    | '/_app/foods/'
    | '/_app/nutrition/'
    | '/_app/foods/$foodId/edit'
    | '/_app/s/$spaceSlug/home'
    | '/_app/s/$spaceSlug/members'
    | '/_app/s/$spaceSlug/modules'
    | '/_app/s/$spaceSlug/settings'
    | '/_app/foods/$foodId/'
    | '/_app/s/$spaceSlug/'
    | '/_app/s/$spaceSlug/recipes/new'
    | '/_app/s/$spaceSlug/settings/dashboard'
    | '/_app/s/$spaceSlug/settings/modules'
    | '/_app/s/$spaceSlug/settings/navigation'
    | '/_app/s/$spaceSlug/nutrition/'
    | '/_app/s/$spaceSlug/recipes/'
    | '/_app/s/$spaceSlug/settings/'
    | '/_app/s/$spaceSlug/recipes/$recipeId/edit'
    | '/_app/s/$spaceSlug/recipes/$recipeId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AboutRoute: typeof AboutRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/wines': {
      id: '/_app/wines'
      path: '/wines'
      fullPath: '/wines'
      preLoaderRoute: typeof AppWinesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pantry': {
      id: '/_app/pantry'
      path: '/pantry'
      fullPath: '/pantry'
      preLoaderRoute: typeof AppPantryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/onboarding': {
      id: '/_app/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notes': {
      id: '/_app/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AppNotesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/meal-planner': {
      id: '/_app/meal-planner'
      path: '/meal-planner'
      fullPath: '/meal-planner'
      preLoaderRoute: typeof AppMealPlannerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/groceries': {
      id: '/_app/groceries'
      path: '/groceries'
      fullPath: '/groceries'
      preLoaderRoute: typeof AppGroceriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finances': {
      id: '/_app/finances'
      path: '/finances'
      fullPath: '/finances'
      preLoaderRoute: typeof AppFinancesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cheeses': {
      id: '/_app/cheeses'
      path: '/cheeses'
      fullPath: '/cheeses'
      preLoaderRoute: typeof AppCheesesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bills': {
      id: '/_app/bills'
      path: '/bills'
      fullPath: '/bills'
      preLoaderRoute: typeof AppBillsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/nutrition/': {
      id: '/_app/nutrition/'
      path: '/nutrition'
      fullPath: '/nutrition/'
      preLoaderRoute: typeof AppNutritionIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/foods/': {
      id: '/_app/foods/'
      path: '/foods'
      fullPath: '/foods/'
      preLoaderRoute: typeof AppFoodsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/s/$spaceSlug': {
      id: '/_app/s/$spaceSlug'
      path: '/s/$spaceSlug'
      fullPath: '/s/$spaceSlug'
      preLoaderRoute: typeof AppSSpaceSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integrations/callback': {
      id: '/_app/integrations/callback'
      path: '/integrations/callback'
      fullPath: '/integrations/callback'
      preLoaderRoute: typeof AppIntegrationsCallbackRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/foods/new': {
      id: '/_app/foods/new'
      path: '/foods/new'
      fullPath: '/foods/new'
      preLoaderRoute: typeof AppFoodsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/s/$spaceSlug/': {
      id: '/_app/s/$spaceSlug/'
      path: '/'
      fullPath: '/s/$spaceSlug/'
      preLoaderRoute: typeof AppSSpaceSlugIndexRouteImport
      parentRoute: typeof AppSSpaceSlugRoute
    }
    '/_app/foods/$foodId/': {
      id: '/_app/foods/$foodId/'
      path: '/foods/$foodId'
      fullPath: '/foods/$foodId/'
      preLoaderRoute: typeof AppFoodsFoodIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/s/$spaceSlug/settings': {
      id: '/_app/s/$spaceSlug/settings'
      path: '/settings'
      fullPath: '/s/$spaceSlug/settings'
      preLoaderRoute: typeof AppSSpaceSlugSettingsRouteImport
      parentRoute: typeof AppSSpaceSlugRoute
    }
    '/_app/s/$spaceSlug/modules': {
      id: '/_app/s/$spaceSlug/modules'
      path: '/modules'
      fullPath: '/s/$spaceSlug/modules'
      preLoaderRoute: typeof AppSSpaceSlugModulesRouteImport
      parentRoute: typeof AppSSpaceSlugRoute
    }
    '/_app/s/$spaceSlug/members': {
      id: '/_app/s/$spaceSlug/members'
      path: '/members'
      fullPath: '/s/$spaceSlug/members'
      preLoaderRoute: typeof AppSSpaceSlugMembersRouteImport
      parentRoute: typeof AppSSpaceSlugRoute
    }
    '/_app/s/$spaceSlug/home': {
      id: '/_app/s/$spaceSlug/home'
      path: '/home'
      fullPath: '/s/$spaceSlug/home'
      preLoaderRoute: typeof AppSSpaceSlugHomeRouteImport
      parentRoute: typeof AppSSpaceSlugRoute
    }
    '/_app/foods/$foodId/edit': {
      id: '/_app/foods/$foodId/edit'
      path: '/foods/$foodId/edit'
      fullPath: '/foods/$foodId/edit'
      preLoaderRoute: typeof AppFoodsFoodIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/s/$spaceSlug/settings/': {
      id: '/_app/s/$spaceSlug/settings/'
      path: '/'
      fullPath: '/s/$spaceSlug/settings/'
      preLoaderRoute: typeof AppSSpaceSlugSettingsIndexRouteImport
      parentRoute: typeof AppSSpaceSlugSettingsRoute
    }
    '/_app/s/$spaceSlug/recipes/': {
      id: '/_app/s/$spaceSlug/recipes/'
      path: '/recipes'
      fullPath: '/s/$spaceSlug/recipes/'
      preLoaderRoute: typeof AppSSpaceSlugRecipesIndexRouteImport
      parentRoute: typeof AppSSpaceSlugRoute
    }
    '/_app/s/$spaceSlug/nutrition/': {
      id: '/_app/s/$spaceSlug/nutrition/'
      path: '/nutrition'
      fullPath: '/s/$spaceSlug/nutrition/'
      preLoaderRoute: typeof AppSSpaceSlugNutritionIndexRouteImport
      parentRoute: typeof AppSSpaceSlugRoute
    }
    '/_app/s/$spaceSlug/settings/navigation': {
      id: '/_app/s/$spaceSlug/settings/navigation'
      path: '/navigation'
      fullPath: '/s/$spaceSlug/settings/navigation'
      preLoaderRoute: typeof AppSSpaceSlugSettingsNavigationRouteImport
      parentRoute: typeof AppSSpaceSlugSettingsRoute
    }
    '/_app/s/$spaceSlug/settings/modules': {
      id: '/_app/s/$spaceSlug/settings/modules'
      path: '/modules'
      fullPath: '/s/$spaceSlug/settings/modules'
      preLoaderRoute: typeof AppSSpaceSlugSettingsModulesRouteImport
      parentRoute: typeof AppSSpaceSlugSettingsRoute
    }
    '/_app/s/$spaceSlug/settings/dashboard': {
      id: '/_app/s/$spaceSlug/settings/dashboard'
      path: '/dashboard'
      fullPath: '/s/$spaceSlug/settings/dashboard'
      preLoaderRoute: typeof AppSSpaceSlugSettingsDashboardRouteImport
      parentRoute: typeof AppSSpaceSlugSettingsRoute
    }
    '/_app/s/$spaceSlug/recipes/new': {
      id: '/_app/s/$spaceSlug/recipes/new'
      path: '/recipes/new'
      fullPath: '/s/$spaceSlug/recipes/new'
      preLoaderRoute: typeof AppSSpaceSlugRecipesNewRouteImport
      parentRoute: typeof AppSSpaceSlugRoute
    }
    '/_app/s/$spaceSlug/recipes/$recipeId/': {
      id: '/_app/s/$spaceSlug/recipes/$recipeId/'
      path: '/recipes/$recipeId'
      fullPath: '/s/$spaceSlug/recipes/$recipeId/'
      preLoaderRoute: typeof AppSSpaceSlugRecipesRecipeIdIndexRouteImport
      parentRoute: typeof AppSSpaceSlugRoute
    }
    '/_app/s/$spaceSlug/recipes/$recipeId/edit': {
      id: '/_app/s/$spaceSlug/recipes/$recipeId/edit'
      path: '/recipes/$recipeId/edit'
      fullPath: '/s/$spaceSlug/recipes/$recipeId/edit'
      preLoaderRoute: typeof AppSSpaceSlugRecipesRecipeIdEditRouteImport
      parentRoute: typeof AppSSpaceSlugRoute
    }
  }
}

interface AppSSpaceSlugSettingsRouteChildren {
  AppSSpaceSlugSettingsDashboardRoute: typeof AppSSpaceSlugSettingsDashboardRoute
  AppSSpaceSlugSettingsModulesRoute: typeof AppSSpaceSlugSettingsModulesRoute
  AppSSpaceSlugSettingsNavigationRoute: typeof AppSSpaceSlugSettingsNavigationRoute
  AppSSpaceSlugSettingsIndexRoute: typeof AppSSpaceSlugSettingsIndexRoute
}

const AppSSpaceSlugSettingsRouteChildren: AppSSpaceSlugSettingsRouteChildren = {
  AppSSpaceSlugSettingsDashboardRoute: AppSSpaceSlugSettingsDashboardRoute,
  AppSSpaceSlugSettingsModulesRoute: AppSSpaceSlugSettingsModulesRoute,
  AppSSpaceSlugSettingsNavigationRoute: AppSSpaceSlugSettingsNavigationRoute,
  AppSSpaceSlugSettingsIndexRoute: AppSSpaceSlugSettingsIndexRoute,
}

const AppSSpaceSlugSettingsRouteWithChildren =
  AppSSpaceSlugSettingsRoute._addFileChildren(
    AppSSpaceSlugSettingsRouteChildren,
  )

interface AppSSpaceSlugRouteChildren {
  AppSSpaceSlugHomeRoute: typeof AppSSpaceSlugHomeRoute
  AppSSpaceSlugMembersRoute: typeof AppSSpaceSlugMembersRoute
  AppSSpaceSlugModulesRoute: typeof AppSSpaceSlugModulesRoute
  AppSSpaceSlugSettingsRoute: typeof AppSSpaceSlugSettingsRouteWithChildren
  AppSSpaceSlugIndexRoute: typeof AppSSpaceSlugIndexRoute
  AppSSpaceSlugRecipesNewRoute: typeof AppSSpaceSlugRecipesNewRoute
  AppSSpaceSlugNutritionIndexRoute: typeof AppSSpaceSlugNutritionIndexRoute
  AppSSpaceSlugRecipesIndexRoute: typeof AppSSpaceSlugRecipesIndexRoute
  AppSSpaceSlugRecipesRecipeIdEditRoute: typeof AppSSpaceSlugRecipesRecipeIdEditRoute
  AppSSpaceSlugRecipesRecipeIdIndexRoute: typeof AppSSpaceSlugRecipesRecipeIdIndexRoute
}

const AppSSpaceSlugRouteChildren: AppSSpaceSlugRouteChildren = {
  AppSSpaceSlugHomeRoute: AppSSpaceSlugHomeRoute,
  AppSSpaceSlugMembersRoute: AppSSpaceSlugMembersRoute,
  AppSSpaceSlugModulesRoute: AppSSpaceSlugModulesRoute,
  AppSSpaceSlugSettingsRoute: AppSSpaceSlugSettingsRouteWithChildren,
  AppSSpaceSlugIndexRoute: AppSSpaceSlugIndexRoute,
  AppSSpaceSlugRecipesNewRoute: AppSSpaceSlugRecipesNewRoute,
  AppSSpaceSlugNutritionIndexRoute: AppSSpaceSlugNutritionIndexRoute,
  AppSSpaceSlugRecipesIndexRoute: AppSSpaceSlugRecipesIndexRoute,
  AppSSpaceSlugRecipesRecipeIdEditRoute: AppSSpaceSlugRecipesRecipeIdEditRoute,
  AppSSpaceSlugRecipesRecipeIdIndexRoute:
    AppSSpaceSlugRecipesRecipeIdIndexRoute,
}

const AppSSpaceSlugRouteWithChildren = AppSSpaceSlugRoute._addFileChildren(
  AppSSpaceSlugRouteChildren,
)

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppBillsRoute: typeof AppBillsRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppCheesesRoute: typeof AppCheesesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFinancesRoute: typeof AppFinancesRoute
  AppGroceriesRoute: typeof AppGroceriesRoute
  AppMealPlannerRoute: typeof AppMealPlannerRoute
  AppNotesRoute: typeof AppNotesRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppPantryRoute: typeof AppPantryRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTasksRoute: typeof AppTasksRoute
  AppWinesRoute: typeof AppWinesRoute
  AppFoodsNewRoute: typeof AppFoodsNewRoute
  AppIntegrationsCallbackRoute: typeof AppIntegrationsCallbackRoute
  AppSSpaceSlugRoute: typeof AppSSpaceSlugRouteWithChildren
  AppFoodsIndexRoute: typeof AppFoodsIndexRoute
  AppNutritionIndexRoute: typeof AppNutritionIndexRoute
  AppFoodsFoodIdEditRoute: typeof AppFoodsFoodIdEditRoute
  AppFoodsFoodIdIndexRoute: typeof AppFoodsFoodIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppBillsRoute: AppBillsRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppCheesesRoute: AppCheesesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFinancesRoute: AppFinancesRoute,
  AppGroceriesRoute: AppGroceriesRoute,
  AppMealPlannerRoute: AppMealPlannerRoute,
  AppNotesRoute: AppNotesRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppPantryRoute: AppPantryRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTasksRoute: AppTasksRoute,
  AppWinesRoute: AppWinesRoute,
  AppFoodsNewRoute: AppFoodsNewRoute,
  AppIntegrationsCallbackRoute: AppIntegrationsCallbackRoute,
  AppSSpaceSlugRoute: AppSSpaceSlugRouteWithChildren,
  AppFoodsIndexRoute: AppFoodsIndexRoute,
  AppNutritionIndexRoute: AppNutritionIndexRoute,
  AppFoodsFoodIdEditRoute: AppFoodsFoodIdEditRoute,
  AppFoodsFoodIdIndexRoute: AppFoodsFoodIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AboutRoute: AboutRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
